namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: Deutsch.</summary>
internal static class De
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Verlauf öffnen",
        ["TrayCapture"] = "Bildschirm aufnehmen",
        ["TraySettings"] = "Einstellungen",
        ["TrayExit"] = "Beenden",
        ["TrayPauseHistory"] = "Zwischenablage-Verlauf pausieren",
        ["TrayResumeHistory"] = "Zwischenablage-Verlauf fortsetzen",
        ["TrayPauseTooltip"] = "Während der Pause wird nichts, was Sie kopieren, im Verlauf gespeichert",

        ["NotifyCaptureCopied"] = "Aufnahme kopiert ({0}x{1})",
        ["NotifyClickToEdit"] = "Zum Bearbeiten klicken",
        ["NotifyHotkeyConflict"] = "Die Tastenkombination {0} wird bereits von einer anderen App verwendet",
        ["NotifyMemoryLimit"] = "Speicherlimit erreicht. Die Aufnahme wurde automatisch abgeschlossen",
        ["NotifyFramesDiscarded"] = "Einige Abschnitte wurden verworfen. Scrollen Sie beim nächsten Mal langsamer",

        ["TabRecent"] = "Zuletzt",
        ["TabFavorites"] = "Favoriten",
        ["TabImages"] = "Bilder und Screenshots",
        ["TabText"] = "Text",
        ["TabFiles"] = "Dateien",
        ["FilterByDate"] = "Nach Datum filtern",
        ["SearchPlaceholder"] = "Verlauf durchsuchen",
        ["EmptyHistory"] = "Noch nichts hier. Kopieren Sie etwas!",
        ["FooterHints"] = "Enter fügt ein · Shift+Enter unformatierter Text · Del löscht",
        ["ClearAll"] = "Alles löschen",
        ["ClearAllTooltip"] = "Entfernt Einträge, die weder angeheftet noch favorisiert sind",
        ["PinTooltip"] = "Oben anheften (Ctrl+P)",
        ["FavoriteTooltip"] = "Zu Favoriten hinzufügen (Ctrl+D)",
        ["MoreOptions"] = "Weitere Optionen",
        ["PinnedBadge"] = "Angeheftet",
        ["FavoriteBadge"] = "Favorit",
        ["DateToday"] = "Heute",
        ["DateYesterday"] = "Gestern",
        ["DateLast7"] = "Letzte 7 Tage",
        ["DateLast30"] = "Letzte 30 Tage",
        ["DateAll"] = "Gesamter Zeitraum",
        ["MenuPaste"] = "Einfügen",
        ["MenuPastePlain"] = "Als unformatierten Text einfügen",
        ["MenuCopy"] = "Kopieren",
        ["MenuSaveAs"] = "Speichern unter...",
        ["MenuOpenInEditor"] = "Im Editor öffnen",
        ["MenuPin"] = "Oben anheften",
        ["MenuUnpin"] = "Lösen",
        ["MenuFavorite"] = "Zu Favoriten hinzufügen",
        ["MenuUnfavorite"] = "Aus Favoriten entfernen",
        ["MenuDelete"] = "Löschen",
        ["GroupPinned"] = "Angeheftet",
        ["GroupRecent"] = "Zuletzt",
        ["ItemImage"] = "Bild",
        ["TimeNow"] = "jetzt",
        ["TimeYesterday"] = "gestern",
        ["PngFilter"] = "PNG-Bild|*.png",

        ["ModeRectangle"] = "Rechteck",
        ["ModeWindow"] = "Fenster",
        ["ModeFullscreen"] = "Vollbild",
        ["ModeScrolling"] = "Scrollende Aufnahme (über den scrollenden Bereich ziehen)",
        ["CloseEsc"] = "Schließen (Esc)",

        ["PanoramicTitle"] = "Scrollende Aufnahme",
        ["PanoramicInstruction"] = "Scrollen Sie den markierten Bereich in Ihrem Tempo,\ngleichmäßig und in eine Richtung.",
        ["PanoramicCaptured"] = "{0} px aufgenommen",
        ["PanoramicSlowDown"] = "Langsamer scrollen",
        ["PanoramicDone"] = "Fertig",
        ["PanoramicCancel"] = "Abbrechen",
        ["CaptureTitleScreen"] = "Bildschirmaufnahme",
        ["CaptureTitleScrolling"] = "Scrollende Aufnahme",

        ["EditorTitle"] = "Klip-Editor",
        ["ToolSelect"] = "Auswählen und verschieben (V)",
        ["ToolPen"] = "Stift (P)",
        ["ToolHighlighter"] = "Textmarker (H)",
        ["ToolEraser"] = "Radierer (E)",
        ["ToolRect"] = "Rechteck (R)",
        ["ToolEllipse"] = "Ellipse (O)",
        ["ToolLine"] = "Linie (L)",
        ["ToolArrow"] = "Pfeil (A)",
        ["ToolText"] = "Text (T)",
        ["ToolCrop"] = "Zuschneiden (C): Enter übernimmt, Esc bricht ab",
        ["ToolRemoveBg"] = "Hintergrund entfernen (einfarbige, mit den Rändern verbundene Hintergründe werden transparent)",
        ["ToolUndo"] = "Rückgängig (Ctrl+Z)",
        ["ToolRedo"] = "Wiederholen (Ctrl+Y)",
        ["ToolAutoCopy"] = "Bei jeder Bearbeitung automatisch kopieren",
        ["ToolSaveAs"] = "Speichern unter... (Ctrl+S)",
        ["Thickness"] = "Stärke",
        ["Zoom"] = "Zoom",
        ["StatusCopied"] = "kopiert",
        ["BgRemoved"] = "Hintergrund entfernt ({0} px transparent)",
        ["BgNotFound"] = "Kein einheitlicher Hintergrund an den Rändern erkannt",
        ["SaveImageFilter"] = "PNG-Bild|*.png|JPEG-Bild|*.jpg",

        ["SettingsTitle"] = "Klip-Einstellungen",
        ["SectionNativeHotkeys"] = "Native Windows-Tastenkombinationen",
        ["CardWinVTitle"] = "Win+V für Klip verwenden",
        ["CardWinVCaption"] = "Deaktiviert das native Verlaufspanel (Registrierungswert DisabledHotkeys) und registriert Win+V für Klip. Startet dabei den Desktop neu. Jederzeit umkehrbar.",
        ["TakeWinV"] = "Win+V übernehmen",
        ["CardCaptureKeyTitle"] = "Native Aufnahme-Tastenkombination",
        ["CardCaptureKeyCaption"] = "Print Screen (empfohlen): löst die PrtSc-Taste vom nativen Snipping Tool, ohne Nebenwirkungen. Win+Shift+S: deaktiviert auch Win+S (Windows-Suche), eine Einschränkung von Windows.",
        ["UsePrintScreen"] = "Print Screen verwenden",
        ["UseWinShiftS"] = "Win+Shift+S verwenden",
        ["CardRevertTitle"] = "Alles zurücksetzen",
        ["CardRevertCaption"] = "Stellt die nativen Windows-Tastenkombinationen exakt wie zuvor wieder her (automatisches Backup) und setzt Klip auf Ctrl+Shift+V / Ctrl+Shift+S zurück.",
        ["Revert"] = "Zurücksetzen",
        ["SectionAppHotkeys"] = "Klip-Tastenkombinationen",
        ["OpenHistoryHotkey"] = "Verlauf öffnen",
        ["NewCaptureHotkey"] = "Neue Aufnahme",
        ["HotkeyHint"] = "Klicken Sie in das Feld und drücken Sie die Kombination",
        ["SectionGeneral"] = "Allgemein",
        ["StartWithWindows"] = "Mit Windows starten",
        ["LanguageTitle"] = "Sprache",
        ["LanguageCaption"] = "Standard: Windows-Sprache. Die Änderung wird sofort übernommen.",
        ["LanguageSystem"] = "System",
        ["LanguageRestart"] = "Sprache gespeichert. Starten Sie Klip neu, um sie anzuwenden.",
        ["SectionClipboard"] = "Zwischenablage-Verlauf",
        ["MaxItemsTitle"] = "Maximale Einträge",
        ["MaxItemsCaption"] = "Angeheftete und favorisierte Einträge werden nie entfernt. 0 = unbegrenzt.",
        ["SectionCapture"] = "Bildschirmaufnahme",
        ["AutoSaveTitle"] = "Aufnahmen automatisch speichern",
        ["AutoSaveCaption"] = "Ordner Bilder\\Screenshots, der Windows-Standard",
        ["CadenceTitle"] = "Frequenz der scrollenden Aufnahme",
        ["CadenceCaption"] = "Intervall zwischen den Frames während des Scrollens (Standard 150 ms; erhöhen, falls der Rechner stockt)",
        ["SectionAbout"] = "Info",
        ["AboutText"] = "Klip: nativer Zwischenablage-Verlauf und Bildschirmaufnahme für Windows 11. Local-first: nichts verlässt Ihren Rechner.",
        ["ItemsInHistory"] = "{0} Eintrag/Einträge im Verlauf.",

        ["WinVActive"] = "Aktiv: Win+V öffnet Klip.",
        ["WinVFreedNotBound"] = "Win+V ist in der Registrierung freigegeben, aber nicht Klip zugewiesen.",
        ["WinVNative"] = "Win+V gehört Windows (natives Panel).",
        ["ManagedPolicyWarning"] = " (Rechner mit Unternehmensrichtlinien: Änderungen können durch die Domäne rückgängig gemacht werden.)",
        ["PrtScActive"] = "Aktiv: Print Screen öffnet die Klip-Aufnahme.",
        ["WinShiftSActive"] = "Aktiv: Win+Shift+S öffnet die Klip-Aufnahme (Win+S deaktiviert).",
        ["PrtScFreeInfo"] = "PrtSc ist im System frei; Klip-Aufnahme liegt auf {0}.",
        ["PrtScNativeInfo"] = "PrtSc öffnet das native Snipping Tool; Klip-Aufnahme liegt auf {0}.",
        ["ConfirmWinV"] = "Klip wird:\n\n1. 'V' zum Registrierungswert DisabledHotkeys (HKCU) hinzufügen, mit automatischem Backup.\n2. Den Desktop neu starten (Explorer-Fenster schließen sich; die Taskleiste blinkt).\n3. Win+V für Klip registrieren.\n\nDas native Verlaufspanel öffnet sich dann nicht mehr. Umkehrbar über die Schaltfläche Zurücksetzen.\n\nFortfahren?",
        ["ConfirmWinVTitle"] = "Win+V übernehmen",
        ["ConfirmHklm"] = "Windows hält Win+V weiterhin (üblich ab 24H2).\n\nPlan B deaktiviert die native Verlaufsfunktion über HKLM (erfordert Administrator). Die Seite 'Zwischenablage' verschwindet aus den Windows-Einstellungen, bis zurückgesetzt wird.\n\nPlan B anwenden?",
        ["ConfirmHklmTitle"] = "Plan B (erfordert Administrator)",
        ["ConfirmWinShiftS"] = "ACHTUNG: Aufgrund einer Windows-Einschränkung deaktiviert das Abschalten von Win+Shift+S auch Win+S (Windows-Suche).\n\nDer empfohlene Weg ist die Print Screen-Taste.\n\nTrotzdem fortfahren? (Startet den Desktop neu)",
        ["ConfirmWinShiftSTitle"] = "Win+Shift+S übernehmen",
        ["ConfirmRevert"] = "Stellt die nativen Windows-Tastenkombinationen aus dem Backup wieder her und setzt Klip auf Ctrl+Shift+V / Ctrl+Shift+S zurück. Startet den Desktop neu.\n\nFortfahren?",
        ["ConfirmRevertTitle"] = "Zurücksetzen",
        ["BusyApplying"] = "Registrierungsänderungen werden angewendet und der Desktop wird neu gestartet...",
        ["BusyReverting"] = "Registrierungsänderungen werden zurückgesetzt und der Desktop wird neu gestartet...",
        ["ResultWinVOk"] = "Fertig! Win+V öffnet jetzt Klip.",
        ["ResultUacCancelled"] = "Bei der UAC abgebrochen. In HKLM wurde nichts geändert.",
        ["ResultWinVFail"] = "Win+V konnte nicht registriert werden. Siehe Log unter %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "Fertig! Print Screen öffnet jetzt die Klip-Aufnahme.",
        ["ResultPrtScConflict"] = "PrtSc freigegeben, aber eine andere App hält die Taste.",
        ["ResultWinShiftSOk"] = "Fertig! Win+Shift+S öffnet jetzt die Klip-Aufnahme.",
        ["ResultWinShiftSFail"] = "Win+Shift+S konnte nicht registriert werden.",
        ["ResultReverted"] = "Native Windows-Tastenkombinationen wiederhergestellt.",
        ["HotkeyUpdated"] = "Tastenkombination aktualisiert: {0}",
        ["HotkeyConflict"] = "{0} steht in Konflikt mit einer anderen Anwendung.",
    };
}
