namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: Español.</summary>
internal static class Es
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Abrir historial",
        ["TrayCapture"] = "Capturar pantalla",
        ["TraySettings"] = "Configuración",
        ["TrayExit"] = "Salir",
        ["TrayPauseHistory"] = "Pausar historial del portapapeles",
        ["TrayResumeHistory"] = "Reanudar historial del portapapeles",
        ["TrayPauseTooltip"] = "Mientras está en pausa, nada de lo que copies se guarda en el historial",

        ["NotifyCaptureCopied"] = "Captura copiada ({0}x{1})",
        ["NotifyClickToEdit"] = "Haz clic para editar",
        ["NotifyHotkeyConflict"] = "El atajo {0} ya está en uso por otra aplicación",
        ["NotifyMemoryLimit"] = "Límite de memoria alcanzado. La captura se finalizó automáticamente",
        ["NotifyFramesDiscarded"] = "Se descartaron algunos fragmentos. Desplázate más despacio la próxima vez",

        ["TabRecent"] = "Recientes",
        ["TabFavorites"] = "Favoritos",
        ["TabImages"] = "Imágenes y capturas",
        ["TabText"] = "Texto",
        ["TabFiles"] = "Archivos",
        ["FilterByDate"] = "Filtrar por fecha",
        ["SearchPlaceholder"] = "Buscar en el historial",
        ["EmptyHistory"] = "Nada por aquí. ¡Copia algo!",
        ["FooterHints"] = "Enter pega · Shift+Enter texto sin formato · Del elimina",
        ["ClearAll"] = "Borrar todo",
        ["ClearAllTooltip"] = "Elimina los elementos que no están fijados ni en favoritos",
        ["PinTooltip"] = "Fijar arriba (Ctrl+P)",
        ["FavoriteTooltip"] = "Marcar como favorito (Ctrl+D)",
        ["MoreOptions"] = "Más opciones",
        ["PinnedBadge"] = "Fijado",
        ["FavoriteBadge"] = "Favorito",
        ["DateToday"] = "Hoy",
        ["DateYesterday"] = "Ayer",
        ["DateLast7"] = "Últimos 7 días",
        ["DateLast30"] = "Últimos 30 días",
        ["DateAll"] = "Todo el período",
        ["MenuPaste"] = "Pegar",
        ["MenuPastePlain"] = "Pegar como texto sin formato",
        ["MenuCopy"] = "Copiar",
        ["MenuSaveAs"] = "Guardar como...",
        ["MenuOpenInEditor"] = "Abrir en el editor",
        ["MenuPin"] = "Fijar arriba",
        ["MenuUnpin"] = "Desfijar",
        ["MenuFavorite"] = "Marcar como favorito",
        ["MenuUnfavorite"] = "Quitar de favoritos",
        ["MenuDelete"] = "Eliminar",
        ["GroupPinned"] = "Fijados",
        ["GroupRecent"] = "Recientes",
        ["ItemImage"] = "Imagen",
        ["TimeNow"] = "ahora",
        ["TimeYesterday"] = "ayer",
        ["PngFilter"] = "Imagen PNG|*.png",

        ["ModeRectangle"] = "Rectángulo",
        ["ModeWindow"] = "Ventana",
        ["ModeFullscreen"] = "Pantalla completa",
        ["ModeScrolling"] = "Captura con desplazamiento (arrastra sobre el área que se desplaza)",
        ["CloseEsc"] = "Cerrar (Esc)",

        ["PanoramicTitle"] = "Captura con desplazamiento",
        ["PanoramicInstruction"] = "Desplaza el área resaltada a tu ritmo,\nsuavemente y en una sola dirección.",
        ["PanoramicCaptured"] = "{0} px capturados",
        ["PanoramicSlowDown"] = "Desplázate más despacio",
        ["PanoramicDone"] = "Finalizar",
        ["PanoramicCancel"] = "Cancelar",
        ["CaptureTitleScreen"] = "Captura de pantalla",
        ["CaptureTitleScrolling"] = "Captura con desplazamiento",

        ["EditorTitle"] = "Editor de Klip",
        ["ToolSelect"] = "Seleccionar y mover (V)",
        ["ToolPen"] = "Lápiz (P)",
        ["ToolHighlighter"] = "Resaltador (H)",
        ["ToolEraser"] = "Borrador (E)",
        ["ToolRect"] = "Rectángulo (R)",
        ["ToolEllipse"] = "Elipse (O)",
        ["ToolLine"] = "Línea (L)",
        ["ToolArrow"] = "Flecha (A)",
        ["ToolText"] = "Texto (T)",
        ["ToolCrop"] = "Recortar (C): Enter aplica, Esc cancela",
        ["ToolRemoveBg"] = "Quitar fondo (los fondos sólidos conectados a los bordes se vuelven transparentes)",
        ["ToolUndo"] = "Deshacer (Ctrl+Z)",
        ["ToolRedo"] = "Rehacer (Ctrl+Y)",
        ["ToolAutoCopy"] = "Copiar automáticamente con cada edición",
        ["ToolSaveAs"] = "Guardar como... (Ctrl+S)",
        ["Thickness"] = "Grosor",
        ["Zoom"] = "Zoom",
        ["StatusCopied"] = "copiado",
        ["BgRemoved"] = "Fondo eliminado ({0} px transparentes)",
        ["BgNotFound"] = "No se detectó un fondo uniforme en los bordes",
        ["SaveImageFilter"] = "Imagen PNG|*.png|Imagen JPEG|*.jpg",

        ["SettingsTitle"] = "Configuración de Klip",
        ["SectionNativeHotkeys"] = "Atajos nativos de Windows",
        ["CardWinVTitle"] = "Usar Win+V para Klip",
        ["CardWinVCaption"] = "Desactiva el panel de historial nativo (valor de registro DisabledHotkeys) y registra Win+V para Klip. Reinicia el escritorio durante el proceso. Reversible en cualquier momento.",
        ["TakeWinV"] = "Asumir Win+V",
        ["CardCaptureKeyTitle"] = "Atajo nativo de captura",
        ["CardCaptureKeyCaption"] = "Print Screen (recomendado): libera la tecla PrtSc del Snipping Tool nativo, sin efectos secundarios. Win+Shift+S: también desactiva Win+S (Búsqueda de Windows), una limitación de Windows.",
        ["UsePrintScreen"] = "Usar Print Screen",
        ["UseWinShiftS"] = "Usar Win+Shift+S",
        ["CardRevertTitle"] = "Revertir todo",
        ["CardRevertCaption"] = "Restaura los atajos nativos de Windows exactamente como estaban (copia de seguridad automática) y devuelve Klip a Ctrl+Shift+V / Ctrl+Shift+S.",
        ["Revert"] = "Revertir",
        ["SectionAppHotkeys"] = "Atajos de Klip",
        ["OpenHistoryHotkey"] = "Abrir historial",
        ["NewCaptureHotkey"] = "Nueva captura",
        ["HotkeyHint"] = "Haz clic en el campo y pulsa la combinación",
        ["SectionGeneral"] = "General",
        ["StartWithWindows"] = "Iniciar con Windows",
        ["LanguageTitle"] = "Idioma",
        ["LanguageCaption"] = "Predeterminado: idioma de Windows. El cambio se aplica al instante.",
        ["LanguageSystem"] = "Sistema",
        ["LanguageRestart"] = "Idioma guardado. Reinicia Klip para aplicarlo.",
        ["SectionClipboard"] = "Historial del portapapeles",
        ["MaxItemsTitle"] = "Máximo de elementos",
        ["MaxItemsCaption"] = "Los fijados y favoritos nunca se eliminan. 0 = ilimitado.",
        ["SectionCapture"] = "Captura de pantalla",
        ["AutoSaveTitle"] = "Guardar capturas automáticamente",
        ["AutoSaveCaption"] = "Carpeta Imágenes\\Screenshots, la predeterminada de Windows",
        ["CadenceTitle"] = "Cadencia de la captura con desplazamiento",
        ["CadenceCaption"] = "Intervalo entre fotogramas mientras te desplazas (predeterminado 150 ms; auméntalo si el equipo se traba)",
        ["SectionAbout"] = "Acerca de",
        ["AboutText"] = "Klip: historial de portapapeles y captura de pantalla nativos de Windows 11. Local primero: nada sale de tu equipo.",
        ["ItemsInHistory"] = "{0} elemento(s) en el historial.",

        ["WinVActive"] = "Activo: Win+V abre Klip.",
        ["WinVFreedNotBound"] = "Win+V está liberado en el registro, pero no asignado a Klip.",
        ["WinVNative"] = "Win+V pertenece a Windows (panel nativo).",
        ["ManagedPolicyWarning"] = " (Equipo con políticas corporativas: el dominio puede revertir los cambios.)",
        ["PrtScActive"] = "Activo: Print Screen abre la captura de Klip.",
        ["WinShiftSActive"] = "Activo: Win+Shift+S abre la captura de Klip (Win+S desactivado).",
        ["PrtScFreeInfo"] = "PrtSc está libre en el sistema; la captura de Klip está en {0}.",
        ["PrtScNativeInfo"] = "PrtSc abre el Snipping Tool nativo; la captura de Klip está en {0}.",
        ["ConfirmWinV"] = "Klip va a:\n\n1. Añadir 'V' al valor DisabledHotkeys del registro (HKCU), con copia de seguridad automática.\n2. Reiniciar el escritorio (las ventanas del Explorador se cierran; la barra de tareas parpadea).\n3. Registrar Win+V para Klip.\n\nEl panel de historial nativo deja de abrirse. Reversible con el botón Revertir.\n\n¿Continuar?",
        ["ConfirmWinVTitle"] = "Asumir Win+V",
        ["ConfirmHklm"] = "Windows aún retiene Win+V (habitual en 24H2 o más reciente).\n\nEl plan B desactiva la función nativa de historial mediante HKLM (requiere administrador). La página 'Portapapeles' desaparece de la Configuración de Windows hasta revertirlo.\n\n¿Aplicar el plan B?",
        ["ConfirmHklmTitle"] = "Plan B (requiere administrador)",
        ["ConfirmWinShiftS"] = "ATENCIÓN: por una limitación de Windows, desactivar Win+Shift+S también desactiva Win+S (Búsqueda de Windows).\n\nLa vía recomendada es la tecla Print Screen.\n\n¿Continuar de todos modos? (Reinicia el escritorio)",
        ["ConfirmWinShiftSTitle"] = "Asumir Win+Shift+S",
        ["ConfirmRevert"] = "Restaura los atajos nativos de Windows desde la copia de seguridad y devuelve Klip a Ctrl+Shift+V / Ctrl+Shift+S. Reinicia el escritorio.\n\n¿Continuar?",
        ["ConfirmRevertTitle"] = "Revertir",
        ["BusyApplying"] = "Aplicando cambios en el registro y reiniciando el escritorio...",
        ["BusyReverting"] = "Revirtiendo cambios en el registro y reiniciando el escritorio...",
        ["ResultWinVOk"] = "¡Listo! Win+V ahora abre Klip.",
        ["ResultUacCancelled"] = "Cancelado en el UAC. No se cambió nada en HKLM.",
        ["ResultWinVFail"] = "No se pudo registrar Win+V. Revisa el log en %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "¡Listo! Print Screen ahora abre la captura de Klip.",
        ["ResultPrtScConflict"] = "PrtSc liberado, pero otra aplicación retiene la tecla.",
        ["ResultWinShiftSOk"] = "¡Listo! Win+Shift+S ahora abre la captura de Klip.",
        ["ResultWinShiftSFail"] = "No se pudo registrar Win+Shift+S.",
        ["ResultReverted"] = "Atajos nativos de Windows restaurados.",
        ["HotkeyUpdated"] = "Atajo actualizado: {0}",
        ["HotkeyConflict"] = "{0} está en conflicto con otra aplicación.",
    };
}
