namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: Français.</summary>
internal static class Fr
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Ouvrir l'historique",
        ["TrayCapture"] = "Capturer l'écran",
        ["TraySettings"] = "Paramètres",
        ["TrayExit"] = "Quitter",
        ["TrayPauseHistory"] = "Suspendre l'historique du presse-papiers",
        ["TrayResumeHistory"] = "Reprendre l'historique du presse-papiers",
        ["TrayPauseTooltip"] = "Pendant la pause, rien de ce que vous copiez n'est enregistré dans l'historique",

        ["NotifyCaptureCopied"] = "Capture copiée ({0}x{1})",
        ["NotifyClickToEdit"] = "Cliquez pour modifier",
        ["NotifyHotkeyConflict"] = "Le raccourci {0} est déjà utilisé par une autre application",
        ["NotifyMemoryLimit"] = "Limite de mémoire atteinte. La capture a été terminée automatiquement",
        ["NotifyFramesDiscarded"] = "Certaines portions ont été ignorées. Faites défiler plus lentement la prochaine fois",

        ["TabRecent"] = "Récents",
        ["TabFavorites"] = "Favoris",
        ["TabImages"] = "Images et captures",
        ["TabText"] = "Texte",
        ["TabFiles"] = "Fichiers",
        ["FilterByDate"] = "Filtrer par date",
        ["SearchPlaceholder"] = "Rechercher dans l'historique",
        ["EmptyHistory"] = "Rien ici pour l'instant. Copiez quelque chose !",
        ["FooterHints"] = "Enter colle · Shift+Enter texte brut · Del supprime",
        ["ClearAll"] = "Tout effacer",
        ["ClearAllTooltip"] = "Supprime les éléments ni épinglés ni favoris",
        ["PinTooltip"] = "Épingler en haut (Ctrl+P)",
        ["FavoriteTooltip"] = "Ajouter aux favoris (Ctrl+D)",
        ["MoreOptions"] = "Plus d'options",
        ["PinnedBadge"] = "Épinglé",
        ["FavoriteBadge"] = "Favori",
        ["DateToday"] = "Aujourd'hui",
        ["DateYesterday"] = "Hier",
        ["DateLast7"] = "7 derniers jours",
        ["DateLast30"] = "30 derniers jours",
        ["DateAll"] = "Toute la période",
        ["MenuPaste"] = "Coller",
        ["MenuPastePlain"] = "Coller en texte brut",
        ["MenuCopy"] = "Copier",
        ["MenuSaveAs"] = "Enregistrer sous...",
        ["MenuOpenInEditor"] = "Ouvrir dans l'éditeur",
        ["MenuPin"] = "Épingler en haut",
        ["MenuUnpin"] = "Désépingler",
        ["MenuFavorite"] = "Ajouter aux favoris",
        ["MenuUnfavorite"] = "Retirer des favoris",
        ["MenuDelete"] = "Supprimer",
        ["GroupPinned"] = "Épinglés",
        ["GroupRecent"] = "Récents",
        ["ItemImage"] = "Image",
        ["TimeNow"] = "à l'instant",
        ["TimeYesterday"] = "hier",
        ["PngFilter"] = "Image PNG|*.png",

        ["ModeRectangle"] = "Rectangle",
        ["ModeWindow"] = "Fenêtre",
        ["ModeFullscreen"] = "Plein écran",
        ["ModeScrolling"] = "Capture avec défilement (faites glisser sur la zone qui défile)",
        ["CloseEsc"] = "Fermer (Esc)",

        ["PanoramicTitle"] = "Capture avec défilement",
        ["PanoramicInstruction"] = "Faites défiler la zone en surbrillance à votre rythme,\nen douceur et dans une seule direction.",
        ["PanoramicCaptured"] = "{0} px capturés",
        ["PanoramicSlowDown"] = "Faites défiler plus lentement",
        ["PanoramicDone"] = "Terminer",
        ["PanoramicCancel"] = "Annuler",
        ["CaptureTitleScreen"] = "Capture d'écran",
        ["CaptureTitleScrolling"] = "Capture avec défilement",

        ["EditorTitle"] = "Éditeur Klip",
        ["ToolSelect"] = "Sélectionner et déplacer (V)",
        ["ToolPen"] = "Stylo (P)",
        ["ToolHighlighter"] = "Surligneur (H)",
        ["ToolEraser"] = "Gomme (E)",
        ["ToolRect"] = "Rectangle (R)",
        ["ToolEllipse"] = "Ellipse (O)",
        ["ToolLine"] = "Ligne (L)",
        ["ToolArrow"] = "Flèche (A)",
        ["ToolText"] = "Texte (T)",
        ["ToolCrop"] = "Rogner (C) : Enter applique, Esc annule",
        ["ToolRemoveBg"] = "Supprimer l'arrière-plan (les fonds unis reliés aux bords deviennent transparents)",
        ["ToolUndo"] = "Annuler (Ctrl+Z)",
        ["ToolRedo"] = "Rétablir (Ctrl+Y)",
        ["ToolAutoCopy"] = "Copier automatiquement à chaque modification",
        ["ToolSaveAs"] = "Enregistrer sous... (Ctrl+S)",
        ["Thickness"] = "Épaisseur",
        ["Zoom"] = "Zoom",
        ["StatusCopied"] = "copié",
        ["BgRemoved"] = "Arrière-plan supprimé ({0} px transparents)",
        ["BgNotFound"] = "Aucun fond uniforme détecté sur les bords",
        ["SaveImageFilter"] = "Image PNG|*.png|Image JPEG|*.jpg",

        ["SettingsTitle"] = "Paramètres de Klip",
        ["SectionNativeHotkeys"] = "Raccourcis natifs de Windows",
        ["CardWinVTitle"] = "Utiliser Win+V pour Klip",
        ["CardWinVCaption"] = "Désactive le panneau d'historique natif (valeur de registre DisabledHotkeys) et enregistre Win+V pour Klip. Redémarre le Bureau au passage. Réversible à tout moment.",
        ["TakeWinV"] = "Prendre Win+V",
        ["CardCaptureKeyTitle"] = "Raccourci natif de capture",
        ["CardCaptureKeyCaption"] = "Print Screen (recommandé) : libère la touche PrtSc du Snipping Tool natif, sans effets secondaires. Win+Shift+S : désactive aussi Win+S (Recherche Windows), une limitation de Windows.",
        ["UsePrintScreen"] = "Utiliser Print Screen",
        ["UseWinShiftS"] = "Utiliser Win+Shift+S",
        ["CardRevertTitle"] = "Tout rétablir",
        ["CardRevertCaption"] = "Restaure les raccourcis natifs de Windows exactement comme ils étaient (sauvegarde automatique) et ramène Klip à Ctrl+Shift+V / Ctrl+Shift+S.",
        ["Revert"] = "Rétablir",
        ["SectionAppHotkeys"] = "Raccourcis de Klip",
        ["OpenHistoryHotkey"] = "Ouvrir l'historique",
        ["NewCaptureHotkey"] = "Nouvelle capture",
        ["HotkeyHint"] = "Cliquez dans le champ et appuyez sur la combinaison",
        ["SectionGeneral"] = "Général",
        ["StartWithWindows"] = "Démarrer avec Windows",
        ["LanguageTitle"] = "Langue",
        ["LanguageCaption"] = "Par défaut : langue de Windows. Le changement s'applique immédiatement.",
        ["LanguageSystem"] = "Système",
        ["LanguageRestart"] = "Langue enregistrée. Redémarrez Klip pour l'appliquer.",
        ["SectionClipboard"] = "Historique du presse-papiers",
        ["MaxItemsTitle"] = "Nombre maximal d'éléments",
        ["MaxItemsCaption"] = "Les éléments épinglés et favoris ne sont jamais supprimés. 0 = illimité.",
        ["SectionCapture"] = "Capture d'écran",
        ["AutoSaveTitle"] = "Enregistrer les captures automatiquement",
        ["AutoSaveCaption"] = "Dossier Images\\Screenshots, le dossier par défaut de Windows",
        ["CadenceTitle"] = "Cadence de la capture avec défilement",
        ["CadenceCaption"] = "Intervalle entre les images pendant le défilement (150 ms par défaut ; augmentez si la machine saccade)",
        ["SectionAbout"] = "À propos",
        ["AboutText"] = "Klip : historique du presse-papiers et capture d'écran natifs de Windows 11. Local d'abord : rien ne quitte votre machine.",
        ["ItemsInHistory"] = "{0} élément(s) dans l'historique.",

        ["WinVActive"] = "Actif : Win+V ouvre Klip.",
        ["WinVFreedNotBound"] = "Win+V est libéré dans le registre, mais pas attribué à Klip.",
        ["WinVNative"] = "Win+V appartient à Windows (panneau natif).",
        ["ManagedPolicyWarning"] = " (Machine avec des stratégies d'entreprise : les modifications peuvent être annulées par le domaine.)",
        ["PrtScActive"] = "Actif : Print Screen ouvre la capture de Klip.",
        ["WinShiftSActive"] = "Actif : Win+Shift+S ouvre la capture de Klip (Win+S désactivé).",
        ["PrtScFreeInfo"] = "PrtSc est libre dans le système ; la capture de Klip est sur {0}.",
        ["PrtScNativeInfo"] = "PrtSc ouvre le Snipping Tool natif ; la capture de Klip est sur {0}.",
        ["ConfirmWinV"] = "Klip va :\n\n1. Ajouter 'V' à la valeur de registre DisabledHotkeys (HKCU), avec sauvegarde automatique.\n2. Redémarrer le Bureau (les fenêtres de l'Explorateur se ferment ; la barre des tâches clignote).\n3. Enregistrer Win+V pour Klip.\n\nLe panneau d'historique natif ne s'ouvrira plus. Réversible via le bouton Rétablir.\n\nContinuer ?",
        ["ConfirmWinVTitle"] = "Prendre Win+V",
        ["ConfirmHklm"] = "Windows retient encore Win+V (courant sur 24H2 ou plus récent).\n\nLe plan B désactive la fonction d'historique native via HKLM (requiert un administrateur). La page 'Presse-papiers' disparaît des Paramètres Windows jusqu'au rétablissement.\n\nAppliquer le plan B ?",
        ["ConfirmHklmTitle"] = "Plan B (requiert un administrateur)",
        ["ConfirmWinShiftS"] = "ATTENTION : en raison d'une limitation de Windows, désactiver Win+Shift+S désactive aussi Win+S (Recherche Windows).\n\nLa voie recommandée est la touche Print Screen.\n\nContinuer quand même ? (Redémarre le Bureau)",
        ["ConfirmWinShiftSTitle"] = "Prendre Win+Shift+S",
        ["ConfirmRevert"] = "Restaure les raccourcis natifs de Windows depuis la sauvegarde et ramène Klip à Ctrl+Shift+V / Ctrl+Shift+S. Redémarre le Bureau.\n\nContinuer ?",
        ["ConfirmRevertTitle"] = "Rétablir",
        ["BusyApplying"] = "Application des modifications du registre et redémarrage du Bureau...",
        ["BusyReverting"] = "Annulation des modifications du registre et redémarrage du Bureau...",
        ["ResultWinVOk"] = "C'est fait ! Win+V ouvre maintenant Klip.",
        ["ResultUacCancelled"] = "Annulé au niveau de l'UAC. Rien n'a été modifié dans HKLM.",
        ["ResultWinVFail"] = "Impossible d'enregistrer Win+V. Consultez le journal dans %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "C'est fait ! Print Screen ouvre maintenant la capture de Klip.",
        ["ResultPrtScConflict"] = "PrtSc libéré, mais une autre application retient la touche.",
        ["ResultWinShiftSOk"] = "C'est fait ! Win+Shift+S ouvre maintenant la capture de Klip.",
        ["ResultWinShiftSFail"] = "Impossible d'enregistrer Win+Shift+S.",
        ["ResultReverted"] = "Raccourcis natifs de Windows restaurés.",
        ["HotkeyUpdated"] = "Raccourci mis à jour : {0}",
        ["HotkeyConflict"] = "{0} est en conflit avec une autre application.",
    };
}
