namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: 日本語.</summary>
internal static class Ja
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "履歴を開く",
        ["TrayCapture"] = "画面をキャプチャ",
        ["TraySettings"] = "設定",
        ["TrayExit"] = "終了",
        ["TrayPauseHistory"] = "クリップボード履歴を一時停止",
        ["TrayResumeHistory"] = "クリップボード履歴を再開",
        ["TrayPauseTooltip"] = "一時停止中は、コピーした内容は履歴に保存されません",

        ["NotifyCaptureCopied"] = "キャプチャをコピーしました ({0}x{1})",
        ["NotifyClickToEdit"] = "クリックして編集",
        ["NotifyHotkeyConflict"] = "ショートカット {0} は既に別のアプリで使用されています",
        ["NotifyMemoryLimit"] = "メモリの上限に達しました。キャプチャは自動的に終了しました",
        ["NotifyFramesDiscarded"] = "一部の区間が破棄されました。次回はゆっくりスクロールしてください",

        ["TabRecent"] = "最近",
        ["TabFavorites"] = "お気に入り",
        ["TabImages"] = "画像とスクリーンショット",
        ["TabText"] = "テキスト",
        ["TabFiles"] = "ファイル",
        ["FilterByDate"] = "日付でフィルター",
        ["SearchPlaceholder"] = "履歴を検索",
        ["EmptyHistory"] = "まだ何もありません。何かコピーしてみましょう！",
        ["FooterHints"] = "Enter で貼り付け · Shift+Enter でプレーンテキスト · Del で削除",
        ["ClearAll"] = "すべてクリア",
        ["ClearAllTooltip"] = "ピン留めもお気に入りもされていない項目を削除します",
        ["PinTooltip"] = "先頭にピン留め (Ctrl+P)",
        ["FavoriteTooltip"] = "お気に入りに追加 (Ctrl+D)",
        ["MoreOptions"] = "その他のオプション",
        ["PinnedBadge"] = "ピン留め済み",
        ["FavoriteBadge"] = "お気に入り",
        ["DateToday"] = "今日",
        ["DateYesterday"] = "昨日",
        ["DateLast7"] = "過去 7 日間",
        ["DateLast30"] = "過去 30 日間",
        ["DateAll"] = "すべての期間",
        ["MenuPaste"] = "貼り付け",
        ["MenuPastePlain"] = "プレーンテキストとして貼り付け",
        ["MenuCopy"] = "コピー",
        ["MenuSaveAs"] = "名前を付けて保存...",
        ["MenuOpenInEditor"] = "エディターで開く",
        ["MenuPin"] = "先頭にピン留め",
        ["MenuUnpin"] = "ピン留めを解除",
        ["MenuFavorite"] = "お気に入りに追加",
        ["MenuUnfavorite"] = "お気に入りから削除",
        ["MenuDelete"] = "削除",
        ["GroupPinned"] = "ピン留め済み",
        ["GroupRecent"] = "最近",
        ["ItemImage"] = "画像",
        ["TimeNow"] = "たった今",
        ["TimeYesterday"] = "昨日",
        ["PngFilter"] = "PNG 画像|*.png",

        ["ModeRectangle"] = "四角形",
        ["ModeWindow"] = "ウィンドウ",
        ["ModeFullscreen"] = "全画面",
        ["ModeScrolling"] = "スクロールキャプチャ（スクロールする領域をドラッグ）",
        ["CloseEsc"] = "閉じる (Esc)",

        ["PanoramicTitle"] = "スクロールキャプチャ",
        ["PanoramicInstruction"] = "ハイライトされた領域を自分のペースで、\nなめらかに一方向にスクロールしてください。",
        ["PanoramicCaptured"] = "{0} px キャプチャ済み",
        ["PanoramicSlowDown"] = "もっとゆっくりスクロールしてください",
        ["PanoramicDone"] = "完了",
        ["PanoramicCancel"] = "キャンセル",
        ["CaptureTitleScreen"] = "画面キャプチャ",
        ["CaptureTitleScrolling"] = "スクロールキャプチャ",

        ["EditorTitle"] = "Klip エディター",
        ["ToolSelect"] = "選択と移動 (V)",
        ["ToolPen"] = "ペン (P)",
        ["ToolHighlighter"] = "蛍光ペン (H)",
        ["ToolEraser"] = "消しゴム (E)",
        ["ToolRect"] = "四角形 (R)",
        ["ToolEllipse"] = "楕円 (O)",
        ["ToolLine"] = "直線 (L)",
        ["ToolArrow"] = "矢印 (A)",
        ["ToolText"] = "テキスト (T)",
        ["ToolCrop"] = "トリミング (C)：Enter で適用、Esc でキャンセル",
        ["ToolRemoveBg"] = "背景を削除（縁につながった単色の背景が透明になります）",
        ["ToolUndo"] = "元に戻す (Ctrl+Z)",
        ["ToolRedo"] = "やり直す (Ctrl+Y)",
        ["ToolAutoCopy"] = "編集のたびに自動コピー",
        ["ToolSaveAs"] = "名前を付けて保存... (Ctrl+S)",
        ["Thickness"] = "太さ",
        ["Zoom"] = "ズーム",
        ["StatusCopied"] = "コピー済み",
        ["BgRemoved"] = "背景を削除しました（{0} px が透明）",
        ["BgNotFound"] = "縁に均一な背景が検出されませんでした",
        ["SaveImageFilter"] = "PNG 画像|*.png|JPEG 画像|*.jpg",

        ["SettingsTitle"] = "Klip の設定",
        ["SectionNativeHotkeys"] = "Windows ネイティブのショートカット",
        ["CardWinVTitle"] = "Win+V を Klip に使用する",
        ["CardWinVCaption"] = "ネイティブの履歴パネルを無効化し（レジストリの DisabledHotkeys 値）、Win+V を Klip に登録します。処理中にデスクトップが再起動します。いつでも元に戻せます。",
        ["TakeWinV"] = "Win+V を引き継ぐ",
        ["CardCaptureKeyTitle"] = "ネイティブのキャプチャショートカット",
        ["CardCaptureKeyCaption"] = "Print Screen（推奨）：ネイティブの Snipping Tool から PrtSc キーを解放します。副作用はありません。Win+Shift+S：Windows の制限により、Win+S（Windows 検索）も無効になります。",
        ["UsePrintScreen"] = "Print Screen を使用",
        ["UseWinShiftS"] = "Win+Shift+S を使用",
        ["CardRevertTitle"] = "すべて元に戻す",
        ["CardRevertCaption"] = "Windows ネイティブのショートカットを元の状態に正確に復元し（自動バックアップ）、Klip を Ctrl+Shift+V / Ctrl+Shift+S に戻します。",
        ["Revert"] = "元に戻す",
        ["SectionAppHotkeys"] = "Klip のショートカット",
        ["OpenHistoryHotkey"] = "履歴を開く",
        ["NewCaptureHotkey"] = "新しいキャプチャ",
        ["HotkeyHint"] = "フィールドをクリックしてキーの組み合わせを押してください",
        ["SectionGeneral"] = "全般",
        ["StartWithWindows"] = "Windows と同時に起動",
        ["LanguageTitle"] = "言語",
        ["LanguageCaption"] = "既定：Windows の言語。変更はすぐに適用されます。",
        ["LanguageSystem"] = "システム",
        ["LanguageRestart"] = "言語を保存しました。適用するには Klip を再起動してください。",
        ["SectionClipboard"] = "クリップボード履歴",
        ["MaxItemsTitle"] = "最大項目数",
        ["MaxItemsCaption"] = "ピン留めとお気に入りの項目は削除されません。0 = 無制限。",
        ["SectionCapture"] = "画面キャプチャ",
        ["AutoSaveTitle"] = "キャプチャを自動保存",
        ["AutoSaveCaption"] = "ピクチャ\\Screenshots フォルダー（Windows の既定）",
        ["CadenceTitle"] = "スクロールキャプチャの間隔",
        ["CadenceCaption"] = "スクロール中のフレーム間隔（既定 150 ms。動作が重い場合は増やしてください）",
        ["SectionAbout"] = "バージョン情報",
        ["AboutText"] = "Klip：Windows 11 ネイティブのクリップボード履歴と画面キャプチャ。ローカルファースト：データがマシンの外に出ることはありません。",
        ["ItemsInHistory"] = "履歴に {0} 件の項目があります。",

        ["WinVActive"] = "有効：Win+V で Klip が開きます。",
        ["WinVFreedNotBound"] = "Win+V はレジストリで解放されていますが、Klip に割り当てられていません。",
        ["WinVNative"] = "Win+V は Windows が使用しています（ネイティブパネル）。",
        ["ManagedPolicyWarning"] = "（企業ポリシーが適用されたマシンです。変更はドメインによって元に戻される可能性があります。）",
        ["PrtScActive"] = "有効：Print Screen で Klip のキャプチャが開きます。",
        ["WinShiftSActive"] = "有効：Win+Shift+S で Klip のキャプチャが開きます（Win+S は無効）。",
        ["PrtScFreeInfo"] = "PrtSc はシステムで空いています。Klip のキャプチャは {0} です。",
        ["PrtScNativeInfo"] = "PrtSc はネイティブの Snipping Tool を開きます。Klip のキャプチャは {0} です。",
        ["ConfirmWinV"] = "Klip は次の操作を行います：\n\n1. レジストリ (HKCU) の DisabledHotkeys 値に 'V' を追加します（自動バックアップ付き）。\n2. デスクトップを再起動します（Explorer のウィンドウが閉じ、タスクバーが点滅します）。\n3. Win+V を Klip に登録します。\n\nネイティブの履歴パネルは開かなくなります。「元に戻す」ボタンでいつでも戻せます。\n\n続行しますか？",
        ["ConfirmWinVTitle"] = "Win+V を引き継ぐ",
        ["ConfirmHklm"] = "Windows がまだ Win+V を保持しています（24H2 以降でよくあります）。\n\nプラン B は HKLM 経由でネイティブの履歴機能を無効化します（管理者権限が必要）。元に戻すまで、Windows の設定から「クリップボード」ページが表示されなくなります。\n\nプラン B を適用しますか？",
        ["ConfirmHklmTitle"] = "プラン B（管理者権限が必要）",
        ["ConfirmWinShiftS"] = "警告：Windows の制限により、Win+Shift+S を無効化すると Win+S（Windows 検索）も無効になります。\n\n推奨は Print Screen キーの使用です。\n\nそれでも続行しますか？（デスクトップが再起動します）",
        ["ConfirmWinShiftSTitle"] = "Win+Shift+S を引き継ぐ",
        ["ConfirmRevert"] = "バックアップから Windows ネイティブのショートカットを復元し、Klip を Ctrl+Shift+V / Ctrl+Shift+S に戻します。デスクトップが再起動します。\n\n続行しますか？",
        ["ConfirmRevertTitle"] = "元に戻す",
        ["BusyApplying"] = "レジストリの変更を適用し、デスクトップを再起動しています...",
        ["BusyReverting"] = "レジストリの変更を元に戻し、デスクトップを再起動しています...",
        ["ResultWinVOk"] = "完了しました。Win+V で Klip が開きます。",
        ["ResultUacCancelled"] = "UAC でキャンセルされました。HKLM は変更されていません。",
        ["ResultWinVFail"] = "Win+V を登録できませんでした。%LocalAppData%\\Klip のログを確認してください。",
        ["ResultPrtScOk"] = "完了しました。Print Screen で Klip のキャプチャが開きます。",
        ["ResultPrtScConflict"] = "PrtSc は解放されましたが、別のアプリがキーを保持しています。",
        ["ResultWinShiftSOk"] = "完了しました。Win+Shift+S で Klip のキャプチャが開きます。",
        ["ResultWinShiftSFail"] = "Win+Shift+S を登録できませんでした。",
        ["ResultReverted"] = "Windows ネイティブのショートカットを復元しました。",
        ["HotkeyUpdated"] = "ショートカットを更新しました：{0}",
        ["HotkeyConflict"] = "{0} は別のアプリケーションと競合しています。",
    };
}
