namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: Nederlands.</summary>
internal static class Nl
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Geschiedenis openen",
        ["TrayCapture"] = "Scherm vastleggen",
        ["TraySettings"] = "Instellingen",
        ["TrayExit"] = "Afsluiten",
        ["TrayPauseHistory"] = "Klembordgeschiedenis pauzeren",
        ["TrayResumeHistory"] = "Klembordgeschiedenis hervatten",
        ["TrayPauseTooltip"] = "Tijdens de pauze wordt niets dat je kopieert in de geschiedenis opgeslagen",

        ["NotifyCaptureCopied"] = "Opname gekopieerd ({0}x{1})",
        ["NotifyClickToEdit"] = "Klik om te bewerken",
        ["NotifyHotkeyConflict"] = "De sneltoets {0} is al in gebruik door een andere app",
        ["NotifyMemoryLimit"] = "Geheugenlimiet bereikt. De opname is automatisch voltooid",
        ["NotifyFramesDiscarded"] = "Sommige delen zijn overgeslagen. Scrol de volgende keer langzamer",

        ["TabRecent"] = "Recent",
        ["TabFavorites"] = "Favorieten",
        ["TabImages"] = "Afbeeldingen en schermafbeeldingen",
        ["TabText"] = "Tekst",
        ["TabFiles"] = "Bestanden",
        ["FilterByDate"] = "Filteren op datum",
        ["SearchPlaceholder"] = "Zoeken in geschiedenis",
        ["EmptyHistory"] = "Nog niets hier. Kopieer iets!",
        ["FooterHints"] = "Enter plakt · Shift+Enter platte tekst · Del verwijdert",
        ["ClearAll"] = "Alles wissen",
        ["ClearAllTooltip"] = "Verwijdert items die niet vastgezet of favoriet zijn",
        ["PinTooltip"] = "Bovenaan vastzetten (Ctrl+P)",
        ["FavoriteTooltip"] = "Aan favorieten toevoegen (Ctrl+D)",
        ["MoreOptions"] = "Meer opties",
        ["PinnedBadge"] = "Vastgezet",
        ["FavoriteBadge"] = "Favoriet",
        ["DateToday"] = "Vandaag",
        ["DateYesterday"] = "Gisteren",
        ["DateLast7"] = "Laatste 7 dagen",
        ["DateLast30"] = "Laatste 30 dagen",
        ["DateAll"] = "Alles",
        ["MenuPaste"] = "Plakken",
        ["MenuPastePlain"] = "Plakken als platte tekst",
        ["MenuCopy"] = "Kopiëren",
        ["MenuSaveAs"] = "Opslaan als...",
        ["MenuOpenInEditor"] = "Openen in editor",
        ["MenuPin"] = "Bovenaan vastzetten",
        ["MenuUnpin"] = "Losmaken",
        ["MenuFavorite"] = "Aan favorieten toevoegen",
        ["MenuUnfavorite"] = "Uit favorieten verwijderen",
        ["MenuDelete"] = "Verwijderen",
        ["GroupPinned"] = "Vastgezet",
        ["GroupRecent"] = "Recent",
        ["ItemImage"] = "Afbeelding",
        ["TimeNow"] = "nu",
        ["TimeYesterday"] = "gisteren",
        ["PngFilter"] = "PNG-afbeelding|*.png",

        ["ModeRectangle"] = "Rechthoek",
        ["ModeWindow"] = "Venster",
        ["ModeFullscreen"] = "Volledig scherm",
        ["ModeScrolling"] = "Scrollende opname (sleep over het gebied dat scrolt)",
        ["CloseEsc"] = "Sluiten (Esc)",

        ["PanoramicTitle"] = "Scrollende opname",
        ["PanoramicInstruction"] = "Scrol het gemarkeerde gebied in je eigen tempo,\nsoepel en in één richting.",
        ["PanoramicCaptured"] = "{0} px vastgelegd",
        ["PanoramicSlowDown"] = "Scrol langzamer",
        ["PanoramicDone"] = "Voltooien",
        ["PanoramicCancel"] = "Annuleren",
        ["CaptureTitleScreen"] = "Schermopname",
        ["CaptureTitleScrolling"] = "Scrollende opname",

        ["EditorTitle"] = "Klip-editor",
        ["ToolSelect"] = "Selecteren en verplaatsen (V)",
        ["ToolPen"] = "Pen (P)",
        ["ToolHighlighter"] = "Markeerstift (H)",
        ["ToolEraser"] = "Gum (E)",
        ["ToolRect"] = "Rechthoek (R)",
        ["ToolEllipse"] = "Ellips (O)",
        ["ToolLine"] = "Lijn (L)",
        ["ToolArrow"] = "Pijl (A)",
        ["ToolText"] = "Tekst (T)",
        ["ToolCrop"] = "Bijsnijden (C): Enter past toe, Esc annuleert",
        ["ToolRemoveBg"] = "Achtergrond verwijderen (egale achtergronden die aan de randen grenzen worden transparant)",
        ["ToolUndo"] = "Ongedaan maken (Ctrl+Z)",
        ["ToolRedo"] = "Opnieuw uitvoeren (Ctrl+Y)",
        ["ToolAutoCopy"] = "Automatisch kopiëren bij elke bewerking",
        ["ToolSaveAs"] = "Opslaan als... (Ctrl+S)",
        ["Thickness"] = "Dikte",
        ["Zoom"] = "Zoom",
        ["StatusCopied"] = "gekopieerd",
        ["BgRemoved"] = "Achtergrond verwijderd ({0} px transparant)",
        ["BgNotFound"] = "Geen egale achtergrond gevonden aan de randen",
        ["SaveImageFilter"] = "PNG-afbeelding|*.png|JPEG-afbeelding|*.jpg",

        ["SettingsTitle"] = "Klip-instellingen",
        ["SectionNativeHotkeys"] = "Systeemeigen Windows-sneltoetsen",
        ["CardWinVTitle"] = "Win+V gebruiken voor Klip",
        ["CardWinVCaption"] = "Schakelt het systeemeigen geschiedenispaneel uit (registerwaarde DisabledHotkeys) en registreert Win+V voor Klip. Herstart daarbij het bureaublad. Op elk moment omkeerbaar.",
        ["TakeWinV"] = "Win+V overnemen",
        ["CardCaptureKeyTitle"] = "Systeemeigen opnamesneltoets",
        ["CardCaptureKeyCaption"] = "Print Screen (aanbevolen): maakt de PrtSc-toets vrij van de systeemeigen Snipping Tool, zonder bijwerkingen. Win+Shift+S: schakelt ook Win+S (Windows Zoeken) uit, een beperking van Windows.",
        ["UsePrintScreen"] = "Print Screen gebruiken",
        ["UseWinShiftS"] = "Win+Shift+S gebruiken",
        ["CardRevertTitle"] = "Alles terugzetten",
        ["CardRevertCaption"] = "Herstelt de systeemeigen Windows-sneltoetsen precies zoals ze waren (automatische back-up) en zet Klip terug naar Ctrl+Shift+V / Ctrl+Shift+S.",
        ["Revert"] = "Terugzetten",
        ["SectionAppHotkeys"] = "Klip-sneltoetsen",
        ["OpenHistoryHotkey"] = "Geschiedenis openen",
        ["NewCaptureHotkey"] = "Nieuwe opname",
        ["HotkeyHint"] = "Klik in het veld en druk op de combinatie",
        ["SectionGeneral"] = "Algemeen",
        ["StartWithWindows"] = "Starten met Windows",
        ["LanguageTitle"] = "Taal",
        ["LanguageCaption"] = "Standaard: de taal van Windows. De wijziging geldt direct.",
        ["LanguageSystem"] = "Systeem",
        ["LanguageRestart"] = "Taal opgeslagen. Herstart Klip om toe te passen.",
        ["SectionClipboard"] = "Klembordgeschiedenis",
        ["MaxItemsTitle"] = "Maximaal aantal items",
        ["MaxItemsCaption"] = "Vastgezette en favoriete items worden nooit verwijderd. 0 = onbeperkt.",
        ["SectionCapture"] = "Schermopname",
        ["AutoSaveTitle"] = "Opnamen automatisch opslaan",
        ["AutoSaveCaption"] = "Map Afbeeldingen\\Screenshots, de standaard van Windows",
        ["CadenceTitle"] = "Interval van de scrollende opname",
        ["CadenceCaption"] = "Interval tussen frames terwijl je scrolt (standaard 150 ms; verhoog dit als de machine hapert)",
        ["SectionAbout"] = "Over",
        ["AboutText"] = "Klip: systeemeigen klembordgeschiedenis en schermopname voor Windows 11. Local-first: niets verlaat je machine.",
        ["ItemsInHistory"] = "{0} item(s) in de geschiedenis.",

        ["WinVActive"] = "Actief: Win+V opent Klip.",
        ["WinVFreedNotBound"] = "Win+V is vrijgegeven in het register, maar niet toegewezen aan Klip.",
        ["WinVNative"] = "Win+V hoort bij Windows (systeemeigen paneel).",
        ["ManagedPolicyWarning"] = " (Machine met bedrijfsbeleid: wijzigingen kunnen door het domein worden teruggedraaid.)",
        ["PrtScActive"] = "Actief: Print Screen opent de opname van Klip.",
        ["WinShiftSActive"] = "Actief: Win+Shift+S opent de opname van Klip (Win+S uitgeschakeld).",
        ["PrtScFreeInfo"] = "PrtSc is vrij in het systeem; de opname van Klip staat op {0}.",
        ["PrtScNativeInfo"] = "PrtSc opent de systeemeigen Snipping Tool; de opname van Klip staat op {0}.",
        ["ConfirmWinV"] = "Klip gaat:\n\n1. 'V' toevoegen aan de registerwaarde DisabledHotkeys (HKCU), met automatische back-up.\n2. Het bureaublad herstarten (Verkenner-vensters sluiten; de taakbalk knippert).\n3. Win+V registreren voor Klip.\n\nHet systeemeigen geschiedenispaneel opent dan niet meer. Omkeerbaar via de knop Terugzetten.\n\nDoorgaan?",
        ["ConfirmWinVTitle"] = "Win+V overnemen",
        ["ConfirmHklm"] = "Windows houdt Win+V nog vast (gebruikelijk op 24H2 of nieuwer).\n\nPlan B schakelt de systeemeigen geschiedenisfunctie uit via HKLM (vereist beheerder). De pagina 'Klembord' verdwijnt uit de Windows-instellingen tot je terugzet.\n\nPlan B toepassen?",
        ["ConfirmHklmTitle"] = "Plan B (vereist beheerder)",
        ["ConfirmWinShiftS"] = "LET OP: door een beperking van Windows schakelt het uitschakelen van Win+Shift+S ook Win+S (Windows Zoeken) uit.\n\nDe aanbevolen route is de Print Screen-toets.\n\nToch doorgaan? (Herstart het bureaublad)",
        ["ConfirmWinShiftSTitle"] = "Win+Shift+S overnemen",
        ["ConfirmRevert"] = "Herstelt de systeemeigen Windows-sneltoetsen vanuit de back-up en zet Klip terug naar Ctrl+Shift+V / Ctrl+Shift+S. Herstart het bureaublad.\n\nDoorgaan?",
        ["ConfirmRevertTitle"] = "Terugzetten",
        ["BusyApplying"] = "Registerwijzigingen toepassen en bureaublad herstarten...",
        ["BusyReverting"] = "Registerwijzigingen terugdraaien en bureaublad herstarten...",
        ["ResultWinVOk"] = "Klaar! Win+V opent nu Klip.",
        ["ResultUacCancelled"] = "Geannuleerd bij UAC. Er is niets gewijzigd in HKLM.",
        ["ResultWinVFail"] = "Kon Win+V niet registreren. Bekijk het logboek in %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "Klaar! Print Screen opent nu de opname van Klip.",
        ["ResultPrtScConflict"] = "PrtSc vrijgegeven, maar een andere app houdt de toets vast.",
        ["ResultWinShiftSOk"] = "Klaar! Win+Shift+S opent nu de opname van Klip.",
        ["ResultWinShiftSFail"] = "Kon Win+Shift+S niet registreren.",
        ["ResultReverted"] = "Systeemeigen Windows-sneltoetsen hersteld.",
        ["HotkeyUpdated"] = "Sneltoets bijgewerkt: {0}",
        ["HotkeyConflict"] = "{0} conflicteert met een andere toepassing.",
    };
}
