namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: polski.</summary>
internal static class Pl
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Otwórz historię",
        ["TrayCapture"] = "Przechwyć ekran",
        ["TraySettings"] = "Ustawienia",
        ["TrayExit"] = "Zakończ",
        ["TrayPauseHistory"] = "Wstrzymaj historię schowka",
        ["TrayResumeHistory"] = "Wznów historię schowka",
        ["TrayPauseTooltip"] = "Podczas wstrzymania nic, co skopiujesz, nie trafia do historii",

        ["NotifyCaptureCopied"] = "Zrzut skopiowany ({0}x{1})",
        ["NotifyClickToEdit"] = "Kliknij, aby edytować",
        ["NotifyHotkeyConflict"] = "Skrót {0} jest już używany przez inną aplikację",
        ["NotifyMemoryLimit"] = "Osiągnięto limit pamięci. Przechwytywanie zakończono automatycznie",
        ["NotifyFramesDiscarded"] = "Część fragmentów została odrzucona. Następnym razem przewijaj wolniej",

        ["TabRecent"] = "Ostatnie",
        ["TabFavorites"] = "Ulubione",
        ["TabImages"] = "Obrazy i zrzuty ekranu",
        ["TabText"] = "Tekst",
        ["TabFiles"] = "Pliki",
        ["FilterByDate"] = "Filtruj według daty",
        ["SearchPlaceholder"] = "Szukaj w historii",
        ["EmptyHistory"] = "Na razie pusto. Skopiuj coś!",
        ["FooterHints"] = "Enter wkleja · Shift+Enter zwykły tekst · Del usuwa",
        ["ClearAll"] = "Wyczyść wszystko",
        ["ClearAllTooltip"] = "Usuwa elementy, które nie są przypięte ani ulubione",
        ["PinTooltip"] = "Przypnij na górze (Ctrl+P)",
        ["FavoriteTooltip"] = "Dodaj do ulubionych (Ctrl+D)",
        ["MoreOptions"] = "Więcej opcji",
        ["PinnedBadge"] = "Przypięte",
        ["FavoriteBadge"] = "Ulubione",
        ["DateToday"] = "Dzisiaj",
        ["DateYesterday"] = "Wczoraj",
        ["DateLast7"] = "Ostatnie 7 dni",
        ["DateLast30"] = "Ostatnie 30 dni",
        ["DateAll"] = "Cały okres",
        ["MenuPaste"] = "Wklej",
        ["MenuPastePlain"] = "Wklej jako zwykły tekst",
        ["MenuCopy"] = "Kopiuj",
        ["MenuSaveAs"] = "Zapisz jako...",
        ["MenuOpenInEditor"] = "Otwórz w edytorze",
        ["MenuPin"] = "Przypnij na górze",
        ["MenuUnpin"] = "Odepnij",
        ["MenuFavorite"] = "Dodaj do ulubionych",
        ["MenuUnfavorite"] = "Usuń z ulubionych",
        ["MenuDelete"] = "Usuń",
        ["GroupPinned"] = "Przypięte",
        ["GroupRecent"] = "Ostatnie",
        ["ItemImage"] = "Obraz",
        ["TimeNow"] = "teraz",
        ["TimeYesterday"] = "wczoraj",
        ["PngFilter"] = "Obraz PNG|*.png",

        ["ModeRectangle"] = "Prostokąt",
        ["ModeWindow"] = "Okno",
        ["ModeFullscreen"] = "Pełny ekran",
        ["ModeScrolling"] = "Przechwytywanie z przewijaniem (przeciągnij po przewijanym obszarze)",
        ["CloseEsc"] = "Zamknij (Esc)",

        ["PanoramicTitle"] = "Przechwytywanie z przewijaniem",
        ["PanoramicInstruction"] = "Przewijaj wyróżniony obszar we własnym tempie,\npłynnie i w jednym kierunku.",
        ["PanoramicCaptured"] = "Przechwycono {0} px",
        ["PanoramicSlowDown"] = "Przewijaj wolniej",
        ["PanoramicDone"] = "Zakończ",
        ["PanoramicCancel"] = "Anuluj",
        ["CaptureTitleScreen"] = "Zrzut ekranu",
        ["CaptureTitleScrolling"] = "Przechwytywanie z przewijaniem",

        ["EditorTitle"] = "Edytor Klip",
        ["ToolSelect"] = "Zaznacz i przesuń (V)",
        ["ToolPen"] = "Pióro (P)",
        ["ToolHighlighter"] = "Zakreślacz (H)",
        ["ToolEraser"] = "Gumka (E)",
        ["ToolRect"] = "Prostokąt (R)",
        ["ToolEllipse"] = "Elipsa (O)",
        ["ToolLine"] = "Linia (L)",
        ["ToolArrow"] = "Strzałka (A)",
        ["ToolText"] = "Tekst (T)",
        ["ToolCrop"] = "Przytnij (C): Enter zatwierdza, Esc anuluje",
        ["ToolRemoveBg"] = "Usuń tło (jednolite tła połączone z krawędziami stają się przezroczyste)",
        ["ToolUndo"] = "Cofnij (Ctrl+Z)",
        ["ToolRedo"] = "Ponów (Ctrl+Y)",
        ["ToolAutoCopy"] = "Kopiuj automatycznie po każdej edycji",
        ["ToolSaveAs"] = "Zapisz jako... (Ctrl+S)",
        ["Thickness"] = "Grubość",
        ["Zoom"] = "Powiększenie",
        ["StatusCopied"] = "skopiowano",
        ["BgRemoved"] = "Tło usunięte ({0} px przezroczystych)",
        ["BgNotFound"] = "Nie wykryto jednolitego tła przy krawędziach",
        ["SaveImageFilter"] = "Obraz PNG|*.png|Obraz JPEG|*.jpg",

        ["SettingsTitle"] = "Ustawienia Klip",
        ["SectionNativeHotkeys"] = "Natywne skróty Windows",
        ["CardWinVTitle"] = "Używaj Win+V dla Klip",
        ["CardWinVCaption"] = "Wyłącza natywny panel historii (wartość rejestru DisabledHotkeys) i rejestruje Win+V dla Klip. Przy okazji restartuje pulpit. Odwracalne w każdej chwili.",
        ["TakeWinV"] = "Przejmij Win+V",
        ["CardCaptureKeyTitle"] = "Natywny skrót przechwytywania",
        ["CardCaptureKeyCaption"] = "Print Screen (zalecane): uwalnia klawisz PrtSc od natywnego Snipping Tool, bez skutków ubocznych. Win+Shift+S: wyłącza też Win+S (wyszukiwanie Windows), ograniczenie systemu Windows.",
        ["UsePrintScreen"] = "Użyj Print Screen",
        ["UseWinShiftS"] = "Użyj Win+Shift+S",
        ["CardRevertTitle"] = "Przywróć wszystko",
        ["CardRevertCaption"] = "Przywraca natywne skróty Windows dokładnie tak, jak były (automatyczna kopia zapasowa) i przywraca Klip do Ctrl+Shift+V / Ctrl+Shift+S.",
        ["Revert"] = "Przywróć",
        ["SectionAppHotkeys"] = "Skróty Klip",
        ["OpenHistoryHotkey"] = "Otwórz historię",
        ["NewCaptureHotkey"] = "Nowe przechwytywanie",
        ["HotkeyHint"] = "Kliknij pole i naciśnij kombinację",
        ["SectionGeneral"] = "Ogólne",
        ["StartWithWindows"] = "Uruchamiaj z systemem Windows",
        ["LanguageTitle"] = "Język",
        ["LanguageCaption"] = "Domyślnie: język systemu Windows. Zmiana działa natychmiast.",
        ["LanguageSystem"] = "Systemowy",
        ["LanguageRestart"] = "Język zapisany. Uruchom Klip ponownie, aby zastosować.",
        ["SectionClipboard"] = "Historia schowka",
        ["MaxItemsTitle"] = "Maksymalna liczba elementów",
        ["MaxItemsCaption"] = "Przypięte i ulubione elementy nigdy nie są usuwane. 0 = bez limitu.",
        ["SectionCapture"] = "Zrzut ekranu",
        ["AutoSaveTitle"] = "Zapisuj zrzuty automatycznie",
        ["AutoSaveCaption"] = "Folder Obrazy\\Screenshots, domyślny dla Windows",
        ["CadenceTitle"] = "Tempo przechwytywania z przewijaniem",
        ["CadenceCaption"] = "Odstęp między klatkami podczas przewijania (domyślnie 150 ms; zwiększ, jeśli komputer się zacina)",
        ["SectionAbout"] = "Informacje",
        ["AboutText"] = "Klip: natywna dla Windows 11 historia schowka i przechwytywanie ekranu. Local-first: nic nie opuszcza Twojego komputera.",
        ["ItemsInHistory"] = "Elementów w historii: {0}.",

        ["WinVActive"] = "Aktywne: Win+V otwiera Klip.",
        ["WinVFreedNotBound"] = "Win+V jest zwolniony w rejestrze, ale nieprzypisany do Klip.",
        ["WinVNative"] = "Win+V należy do Windows (natywny panel).",
        ["ManagedPolicyWarning"] = " (Komputer z zasadami firmowymi: zmiany mogą zostać cofnięte przez domenę.)",
        ["PrtScActive"] = "Aktywne: Print Screen otwiera przechwytywanie Klip.",
        ["WinShiftSActive"] = "Aktywne: Win+Shift+S otwiera przechwytywanie Klip (Win+S wyłączony).",
        ["PrtScFreeInfo"] = "PrtSc jest wolny w systemie; przechwytywanie Klip jest pod {0}.",
        ["PrtScNativeInfo"] = "PrtSc otwiera natywny Snipping Tool; przechwytywanie Klip jest pod {0}.",
        ["ConfirmWinV"] = "Klip wykona następujące kroki:\n\n1. Doda 'V' do wartości rejestru DisabledHotkeys (HKCU), z automatyczną kopią zapasową.\n2. Uruchomi ponownie pulpit (okna Eksploratora zamkną się; pasek zadań mignie).\n3. Zarejestruje Win+V dla Klip.\n\nNatywny panel historii przestanie się otwierać. Odwracalne przyciskiem Przywróć.\n\nKontynuować?",
        ["ConfirmWinVTitle"] = "Przejmij Win+V",
        ["ConfirmHklm"] = "Windows nadal trzyma Win+V (typowe w 24H2 i nowszych).\n\nPlan B wyłącza natywną funkcję historii przez HKLM (wymaga administratora). Strona 'Schowek' zniknie z ustawień Windows do czasu przywrócenia.\n\nZastosować plan B?",
        ["ConfirmHklmTitle"] = "Plan B (wymaga administratora)",
        ["ConfirmWinShiftS"] = "UWAGA: z powodu ograniczenia Windows wyłączenie Win+Shift+S wyłącza także Win+S (wyszukiwanie Windows).\n\nZalecana droga to klawisz Print Screen.\n\nKontynuować mimo to? (Uruchamia ponownie pulpit)",
        ["ConfirmWinShiftSTitle"] = "Przejmij Win+Shift+S",
        ["ConfirmRevert"] = "Przywraca natywne skróty Windows z kopii zapasowej i przywraca Klip do Ctrl+Shift+V / Ctrl+Shift+S. Uruchamia ponownie pulpit.\n\nKontynuować?",
        ["ConfirmRevertTitle"] = "Przywróć",
        ["BusyApplying"] = "Stosowanie zmian w rejestrze i ponowne uruchamianie pulpitu...",
        ["BusyReverting"] = "Cofanie zmian w rejestrze i ponowne uruchamianie pulpitu...",
        ["ResultWinVOk"] = "Gotowe! Win+V otwiera teraz Klip.",
        ["ResultUacCancelled"] = "Anulowano w UAC. Nic nie zmieniono w HKLM.",
        ["ResultWinVFail"] = "Nie udało się zarejestrować Win+V. Sprawdź log w %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "Gotowe! Print Screen otwiera teraz przechwytywanie Klip.",
        ["ResultPrtScConflict"] = "PrtSc zwolniony, ale inna aplikacja trzyma ten klawisz.",
        ["ResultWinShiftSOk"] = "Gotowe! Win+Shift+S otwiera teraz przechwytywanie Klip.",
        ["ResultWinShiftSFail"] = "Nie udało się zarejestrować Win+Shift+S.",
        ["ResultReverted"] = "Natywne skróty Windows przywrócone.",
        ["HotkeyUpdated"] = "Skrót zaktualizowany: {0}",
        ["HotkeyConflict"] = "{0} koliduje z inną aplikacją.",
    };
}
