namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: русский.</summary>
internal static class Ru
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Открыть историю",
        ["TrayCapture"] = "Сделать снимок экрана",
        ["TraySettings"] = "Настройки",
        ["TrayExit"] = "Выход",
        ["TrayPauseHistory"] = "Приостановить историю буфера обмена",
        ["TrayResumeHistory"] = "Возобновить историю буфера обмена",
        ["TrayPauseTooltip"] = "Пока история приостановлена, скопированное не сохраняется",

        ["NotifyCaptureCopied"] = "Снимок скопирован ({0}x{1})",
        ["NotifyClickToEdit"] = "Нажмите, чтобы отредактировать",
        ["NotifyHotkeyConflict"] = "Сочетание {0} уже используется другим приложением",
        ["NotifyMemoryLimit"] = "Достигнут предел памяти. Захват был завершён автоматически",
        ["NotifyFramesDiscarded"] = "Некоторые участки были отброшены. В следующий раз прокручивайте медленнее",

        ["TabRecent"] = "Недавние",
        ["TabFavorites"] = "Избранное",
        ["TabImages"] = "Изображения и снимки",
        ["TabText"] = "Текст",
        ["TabFiles"] = "Файлы",
        ["FilterByDate"] = "Фильтр по дате",
        ["SearchPlaceholder"] = "Поиск по истории",
        ["EmptyHistory"] = "Пока пусто. Скопируйте что-нибудь!",
        ["FooterHints"] = "Enter вставляет · Shift+Enter простой текст · Del удаляет",
        ["ClearAll"] = "Очистить всё",
        ["ClearAllTooltip"] = "Удаляет элементы, которые не закреплены и не в избранном",
        ["PinTooltip"] = "Закрепить сверху (Ctrl+P)",
        ["FavoriteTooltip"] = "В избранное (Ctrl+D)",
        ["MoreOptions"] = "Дополнительно",
        ["PinnedBadge"] = "Закреплено",
        ["FavoriteBadge"] = "Избранное",
        ["DateToday"] = "Сегодня",
        ["DateYesterday"] = "Вчера",
        ["DateLast7"] = "Последние 7 дней",
        ["DateLast30"] = "Последние 30 дней",
        ["DateAll"] = "За всё время",
        ["MenuPaste"] = "Вставить",
        ["MenuPastePlain"] = "Вставить как простой текст",
        ["MenuCopy"] = "Копировать",
        ["MenuSaveAs"] = "Сохранить как...",
        ["MenuOpenInEditor"] = "Открыть в редакторе",
        ["MenuPin"] = "Закрепить сверху",
        ["MenuUnpin"] = "Открепить",
        ["MenuFavorite"] = "В избранное",
        ["MenuUnfavorite"] = "Убрать из избранного",
        ["MenuDelete"] = "Удалить",
        ["GroupPinned"] = "Закреплённые",
        ["GroupRecent"] = "Недавние",
        ["ItemImage"] = "Изображение",
        ["TimeNow"] = "сейчас",
        ["TimeYesterday"] = "вчера",
        ["PngFilter"] = "Изображение PNG|*.png",

        ["ModeRectangle"] = "Прямоугольник",
        ["ModeWindow"] = "Окно",
        ["ModeFullscreen"] = "Весь экран",
        ["ModeScrolling"] = "Захват с прокруткой (выделите область, которая прокручивается)",
        ["CloseEsc"] = "Закрыть (Esc)",

        ["PanoramicTitle"] = "Захват с прокруткой",
        ["PanoramicInstruction"] = "Прокручивайте выделенную область в своём темпе,\nплавно и в одном направлении.",
        ["PanoramicCaptured"] = "Захвачено {0} px",
        ["PanoramicSlowDown"] = "Прокручивайте медленнее",
        ["PanoramicDone"] = "Готово",
        ["PanoramicCancel"] = "Отмена",
        ["CaptureTitleScreen"] = "Снимок экрана",
        ["CaptureTitleScrolling"] = "Захват с прокруткой",

        ["EditorTitle"] = "Редактор Klip",
        ["ToolSelect"] = "Выделение и перемещение (V)",
        ["ToolPen"] = "Перо (P)",
        ["ToolHighlighter"] = "Маркер (H)",
        ["ToolEraser"] = "Ластик (E)",
        ["ToolRect"] = "Прямоугольник (R)",
        ["ToolEllipse"] = "Эллипс (O)",
        ["ToolLine"] = "Линия (L)",
        ["ToolArrow"] = "Стрелка (A)",
        ["ToolText"] = "Текст (T)",
        ["ToolCrop"] = "Обрезка (C): Enter применяет, Esc отменяет",
        ["ToolRemoveBg"] = "Удалить фон (однотонный фон, соединённый с краями, становится прозрачным)",
        ["ToolUndo"] = "Отменить (Ctrl+Z)",
        ["ToolRedo"] = "Повторить (Ctrl+Y)",
        ["ToolAutoCopy"] = "Автоматически копировать при каждом изменении",
        ["ToolSaveAs"] = "Сохранить как... (Ctrl+S)",
        ["Thickness"] = "Толщина",
        ["Zoom"] = "Масштаб",
        ["StatusCopied"] = "скопировано",
        ["BgRemoved"] = "Фон удалён ({0} px прозрачны)",
        ["BgNotFound"] = "Однородный фон по краям не обнаружен",
        ["SaveImageFilter"] = "Изображение PNG|*.png|Изображение JPEG|*.jpg",

        ["SettingsTitle"] = "Настройки Klip",
        ["SectionNativeHotkeys"] = "Системные сочетания Windows",
        ["CardWinVTitle"] = "Использовать Win+V для Klip",
        ["CardWinVCaption"] = "Отключает системную панель истории (значение реестра DisabledHotkeys) и назначает Win+V для Klip. При этом перезапускается рабочий стол. Можно отменить в любой момент.",
        ["TakeWinV"] = "Занять Win+V",
        ["CardCaptureKeyTitle"] = "Системное сочетание для снимков",
        ["CardCaptureKeyCaption"] = "Print Screen (рекомендуется): освобождает клавишу PrtSc от системного Snipping Tool без побочных эффектов. Win+Shift+S: также отключает Win+S (поиск Windows), это ограничение Windows.",
        ["UsePrintScreen"] = "Использовать Print Screen",
        ["UseWinShiftS"] = "Использовать Win+Shift+S",
        ["CardRevertTitle"] = "Вернуть всё как было",
        ["CardRevertCaption"] = "Восстанавливает системные сочетания Windows в точности как были (автоматическая резервная копия) и возвращает Klip на Ctrl+Shift+V / Ctrl+Shift+S.",
        ["Revert"] = "Вернуть",
        ["SectionAppHotkeys"] = "Сочетания Klip",
        ["OpenHistoryHotkey"] = "Открыть историю",
        ["NewCaptureHotkey"] = "Новый снимок",
        ["HotkeyHint"] = "Щёлкните поле и нажмите сочетание клавиш",
        ["SectionGeneral"] = "Общие",
        ["StartWithWindows"] = "Запускать вместе с Windows",
        ["LanguageTitle"] = "Язык",
        ["LanguageCaption"] = "По умолчанию: язык Windows. Изменение применяется сразу.",
        ["LanguageSystem"] = "Системный",
        ["LanguageRestart"] = "Язык сохранён. Перезапустите Klip, чтобы применить.",
        ["SectionClipboard"] = "История буфера обмена",
        ["MaxItemsTitle"] = "Максимум элементов",
        ["MaxItemsCaption"] = "Закреплённые и избранные никогда не удаляются. 0 = без ограничений.",
        ["SectionCapture"] = "Снимок экрана",
        ["AutoSaveTitle"] = "Автоматически сохранять снимки",
        ["AutoSaveCaption"] = "Папка Изображения\\Screenshots, стандартная для Windows",
        ["CadenceTitle"] = "Частота захвата с прокруткой",
        ["CadenceCaption"] = "Интервал между кадрами во время прокрутки (по умолчанию 150 ms; увеличьте, если компьютер тормозит)",
        ["SectionAbout"] = "О программе",
        ["AboutText"] = "Klip: нативные для Windows 11 история буфера обмена и снимки экрана. Local-first: ничего не покидает ваш компьютер.",
        ["ItemsInHistory"] = "Элементов в истории: {0}.",

        ["WinVActive"] = "Активно: Win+V открывает Klip.",
        ["WinVFreedNotBound"] = "Win+V освобождён в реестре, но не назначен Klip.",
        ["WinVNative"] = "Win+V принадлежит Windows (системная панель).",
        ["ManagedPolicyWarning"] = " (Компьютер с корпоративными политиками: изменения могут быть отменены доменом.)",
        ["PrtScActive"] = "Активно: Print Screen открывает захват Klip.",
        ["WinShiftSActive"] = "Активно: Win+Shift+S открывает захват Klip (Win+S отключён).",
        ["PrtScFreeInfo"] = "PrtSc свободен в системе; захват Klip на {0}.",
        ["PrtScNativeInfo"] = "PrtSc открывает системный Snipping Tool; захват Klip на {0}.",
        ["ConfirmWinV"] = "Klip выполнит следующее:\n\n1. Добавит 'V' в значение реестра DisabledHotkeys (HKCU) с автоматической резервной копией.\n2. Перезапустит рабочий стол (окна проводника закроются; панель задач мигнёт).\n3. Назначит Win+V для Klip.\n\nСистемная панель истории перестанет открываться. Отменяется кнопкой «Вернуть».\n\nПродолжить?",
        ["ConfirmWinVTitle"] = "Занять Win+V",
        ["ConfirmHklm"] = "Windows всё ещё удерживает Win+V (типично для 24H2 и новее).\n\nПлан Б отключает системную функцию истории через HKLM (нужны права администратора). Страница «Буфер обмена» исчезнет из настроек Windows до отмены.\n\nПрименить план Б?",
        ["ConfirmHklmTitle"] = "План Б (нужны права администратора)",
        ["ConfirmWinShiftS"] = "ВНИМАНИЕ: из-за ограничения Windows отключение Win+Shift+S также отключает Win+S (поиск Windows).\n\nРекомендуемый вариант: клавиша Print Screen.\n\nВсё равно продолжить? (Перезапустит рабочий стол)",
        ["ConfirmWinShiftSTitle"] = "Занять Win+Shift+S",
        ["ConfirmRevert"] = "Восстанавливает системные сочетания Windows из резервной копии и возвращает Klip на Ctrl+Shift+V / Ctrl+Shift+S. Перезапустит рабочий стол.\n\nПродолжить?",
        ["ConfirmRevertTitle"] = "Вернуть",
        ["BusyApplying"] = "Применение изменений реестра и перезапуск рабочего стола...",
        ["BusyReverting"] = "Отмена изменений реестра и перезапуск рабочего стола...",
        ["ResultWinVOk"] = "Готово! Win+V теперь открывает Klip.",
        ["ResultUacCancelled"] = "Отменено в UAC. В HKLM ничего не изменено.",
        ["ResultWinVFail"] = "Не удалось назначить Win+V. Смотрите журнал в %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "Готово! Print Screen теперь открывает захват Klip.",
        ["ResultPrtScConflict"] = "PrtSc освобождён, но клавишу удерживает другое приложение.",
        ["ResultWinShiftSOk"] = "Готово! Win+Shift+S теперь открывает захват Klip.",
        ["ResultWinShiftSFail"] = "Не удалось назначить Win+Shift+S.",
        ["ResultReverted"] = "Системные сочетания Windows восстановлены.",
        ["HotkeyUpdated"] = "Сочетание обновлено: {0}",
        ["HotkeyConflict"] = "{0} конфликтует с другим приложением.",
    };
}
