namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: Türkçe.</summary>
internal static class Tr
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "Geçmişi aç",
        ["TrayCapture"] = "Ekran yakala",
        ["TraySettings"] = "Ayarlar",
        ["TrayExit"] = "Çıkış",
        ["TrayPauseHistory"] = "Pano geçmişini duraklat",
        ["TrayResumeHistory"] = "Pano geçmişini sürdür",
        ["TrayPauseTooltip"] = "Duraklatılmışken kopyaladıklarınız geçmişe kaydedilmez",

        ["NotifyCaptureCopied"] = "Yakalama kopyalandı ({0}x{1})",
        ["NotifyClickToEdit"] = "Düzenlemek için tıklayın",
        ["NotifyHotkeyConflict"] = "{0} kısayolu zaten başka bir uygulama tarafından kullanılıyor",
        ["NotifyMemoryLimit"] = "Bellek sınırına ulaşıldı. Yakalama otomatik olarak tamamlandı",
        ["NotifyFramesDiscarded"] = "Bazı bölümler atlandı. Bir dahaki sefere daha yavaş kaydırın",

        ["TabRecent"] = "Son kullanılanlar",
        ["TabFavorites"] = "Favoriler",
        ["TabImages"] = "Görseller ve ekran görüntüleri",
        ["TabText"] = "Metin",
        ["TabFiles"] = "Dosyalar",
        ["FilterByDate"] = "Tarihe göre filtrele",
        ["SearchPlaceholder"] = "Geçmişte ara",
        ["EmptyHistory"] = "Henüz bir şey yok. Bir şey kopyalayın!",
        ["FooterHints"] = "Enter yapıştırır · Shift+Enter düz metin · Del siler",
        ["ClearAll"] = "Tümünü temizle",
        ["ClearAllTooltip"] = "Sabitlenmemiş ve favori olmayan öğeleri kaldırır",
        ["PinTooltip"] = "En üste sabitle (Ctrl+P)",
        ["FavoriteTooltip"] = "Favorilere ekle (Ctrl+D)",
        ["MoreOptions"] = "Diğer seçenekler",
        ["PinnedBadge"] = "Sabitlendi",
        ["FavoriteBadge"] = "Favori",
        ["DateToday"] = "Bugün",
        ["DateYesterday"] = "Dün",
        ["DateLast7"] = "Son 7 gün",
        ["DateLast30"] = "Son 30 gün",
        ["DateAll"] = "Tüm zamanlar",
        ["MenuPaste"] = "Yapıştır",
        ["MenuPastePlain"] = "Düz metin olarak yapıştır",
        ["MenuCopy"] = "Kopyala",
        ["MenuSaveAs"] = "Farklı kaydet...",
        ["MenuOpenInEditor"] = "Düzenleyicide aç",
        ["MenuPin"] = "En üste sabitle",
        ["MenuUnpin"] = "Sabitlemeyi kaldır",
        ["MenuFavorite"] = "Favorilere ekle",
        ["MenuUnfavorite"] = "Favorilerden kaldır",
        ["MenuDelete"] = "Sil",
        ["GroupPinned"] = "Sabitlenenler",
        ["GroupRecent"] = "Son kullanılanlar",
        ["ItemImage"] = "Görsel",
        ["TimeNow"] = "şimdi",
        ["TimeYesterday"] = "dün",
        ["PngFilter"] = "PNG görseli|*.png",

        ["ModeRectangle"] = "Dikdörtgen",
        ["ModeWindow"] = "Pencere",
        ["ModeFullscreen"] = "Tam ekran",
        ["ModeScrolling"] = "Kaydırmalı yakalama (kaydırılan alanın üzerine sürükleyin)",
        ["CloseEsc"] = "Kapat (Esc)",

        ["PanoramicTitle"] = "Kaydırmalı yakalama",
        ["PanoramicInstruction"] = "Vurgulanan alanı kendi hızınızda,\nakıcı biçimde ve tek yönde kaydırın.",
        ["PanoramicCaptured"] = "{0} px yakalandı",
        ["PanoramicSlowDown"] = "Daha yavaş kaydırın",
        ["PanoramicDone"] = "Bitir",
        ["PanoramicCancel"] = "İptal",
        ["CaptureTitleScreen"] = "Ekran yakalama",
        ["CaptureTitleScrolling"] = "Kaydırmalı yakalama",

        ["EditorTitle"] = "Klip Düzenleyici",
        ["ToolSelect"] = "Seç ve taşı (V)",
        ["ToolPen"] = "Kalem (P)",
        ["ToolHighlighter"] = "Fosforlu kalem (H)",
        ["ToolEraser"] = "Silgi (E)",
        ["ToolRect"] = "Dikdörtgen (R)",
        ["ToolEllipse"] = "Elips (O)",
        ["ToolLine"] = "Çizgi (L)",
        ["ToolArrow"] = "Ok (A)",
        ["ToolText"] = "Metin (T)",
        ["ToolCrop"] = "Kırp (C): Enter uygular, Esc iptal eder",
        ["ToolRemoveBg"] = "Arka planı kaldır (kenarlara bağlı düz renkli arka planlar saydamlaşır)",
        ["ToolUndo"] = "Geri al (Ctrl+Z)",
        ["ToolRedo"] = "Yinele (Ctrl+Y)",
        ["ToolAutoCopy"] = "Her düzenlemede otomatik kopyala",
        ["ToolSaveAs"] = "Farklı kaydet... (Ctrl+S)",
        ["Thickness"] = "Kalınlık",
        ["Zoom"] = "Yakınlaştırma",
        ["StatusCopied"] = "kopyalandı",
        ["BgRemoved"] = "Arka plan kaldırıldı ({0} px saydam)",
        ["BgNotFound"] = "Kenarlarda tek renkli arka plan bulunamadı",
        ["SaveImageFilter"] = "PNG görseli|*.png|JPEG görseli|*.jpg",

        ["SettingsTitle"] = "Klip Ayarları",
        ["SectionNativeHotkeys"] = "Yerel Windows kısayolları",
        ["CardWinVTitle"] = "Klip için Win+V kullan",
        ["CardWinVCaption"] = "Yerel geçmiş panelini devre dışı bırakır (DisabledHotkeys kayıt defteri değeri) ve Win+V'yi Klip için kaydeder. Bu sırada masaüstünü yeniden başlatır. İstediğiniz zaman geri alınabilir.",
        ["TakeWinV"] = "Win+V'yi devral",
        ["CardCaptureKeyTitle"] = "Yerel yakalama kısayolu",
        ["CardCaptureKeyCaption"] = "Print Screen (önerilen): PrtSc tuşunu yerel Snipping Tool'dan kurtarır, yan etkisi yoktur. Win+Shift+S: Win+S'yi de (Windows Arama) devre dışı bırakır, bu bir Windows kısıtlamasıdır.",
        ["UsePrintScreen"] = "Print Screen kullan",
        ["UseWinShiftS"] = "Win+Shift+S kullan",
        ["CardRevertTitle"] = "Tümünü geri al",
        ["CardRevertCaption"] = "Yerel Windows kısayollarını tam eski haline döndürür (otomatik yedek) ve Klip'u Ctrl+Shift+V / Ctrl+Shift+S kısayollarına geri alır.",
        ["Revert"] = "Geri al",
        ["SectionAppHotkeys"] = "Klip kısayolları",
        ["OpenHistoryHotkey"] = "Geçmişi aç",
        ["NewCaptureHotkey"] = "Yeni yakalama",
        ["HotkeyHint"] = "Alana tıklayın ve tuş bileşimine basın",
        ["SectionGeneral"] = "Genel",
        ["StartWithWindows"] = "Windows ile başlat",
        ["LanguageTitle"] = "Dil",
        ["LanguageCaption"] = "Varsayılan: Windows dili. Değişiklik anında uygulanır.",
        ["LanguageSystem"] = "Sistem",
        ["LanguageRestart"] = "Dil kaydedildi. Uygulamak için Klip'u yeniden başlatın.",
        ["SectionClipboard"] = "Pano geçmişi",
        ["MaxItemsTitle"] = "En fazla öğe",
        ["MaxItemsCaption"] = "Sabitlenenler ve favoriler asla kaldırılmaz. 0 = sınırsız.",
        ["SectionCapture"] = "Ekran yakalama",
        ["AutoSaveTitle"] = "Yakalamaları otomatik kaydet",
        ["AutoSaveCaption"] = "Resimler\\Screenshots klasörü, Windows varsayılanı",
        ["CadenceTitle"] = "Kaydırmalı yakalama temposu",
        ["CadenceCaption"] = "Kaydırma sırasında kareler arası süre (varsayılan 150 ms; makine takılıyorsa artırın)",
        ["SectionAbout"] = "Hakkında",
        ["AboutText"] = "Klip: Windows 11'e özgü pano geçmişi ve ekran yakalama. Local-first: hiçbir şey makinenizden çıkmaz.",
        ["ItemsInHistory"] = "Geçmişte {0} öğe var.",

        ["WinVActive"] = "Etkin: Win+V Klip'u açar.",
        ["WinVFreedNotBound"] = "Win+V kayıt defterinde serbest ama Klip'a atanmamış.",
        ["WinVNative"] = "Win+V Windows'ta (yerel panel).",
        ["ManagedPolicyWarning"] = " (Kurumsal ilkeleri olan makine: değişiklikler etki alanı tarafından geri alınabilir.)",
        ["PrtScActive"] = "Etkin: Print Screen Klip yakalamasını açar.",
        ["WinShiftSActive"] = "Etkin: Win+Shift+S Klip yakalamasını açar (Win+S devre dışı).",
        ["PrtScFreeInfo"] = "PrtSc sistemde serbest; Klip yakalaması {0} üzerinde.",
        ["PrtScNativeInfo"] = "PrtSc yerel Snipping Tool'u açar; Klip yakalaması {0} üzerinde.",
        ["ConfirmWinV"] = "Klip şunları yapacak:\n\n1. Kayıt defterindeki DisabledHotkeys değerine (HKCU) 'V' ekler, otomatik yedekle birlikte.\n2. Masaüstünü yeniden başlatır (Explorer pencereleri kapanır; görev çubuğu yanıp söner).\n3. Win+V'yi Klip için kaydeder.\n\nYerel geçmiş paneli artık açılmaz. Geri al düğmesiyle geri alınabilir.\n\nDevam edilsin mi?",
        ["ConfirmWinVTitle"] = "Win+V'yi devral",
        ["ConfirmHklm"] = "Windows hala Win+V'yi tutuyor (24H2 ve sonrasında yaygın).\n\nB planı, yerel geçmiş özelliğini HKLM üzerinden devre dışı bırakır (yönetici gerektirir). 'Pano' sayfası geri alınana kadar Windows Ayarlarından kaybolur.\n\nB planı uygulansın mı?",
        ["ConfirmHklmTitle"] = "B planı (yönetici gerektirir)",
        ["ConfirmWinShiftS"] = "UYARI: Windows kısıtlaması nedeniyle Win+Shift+S'yi devre dışı bırakmak Win+S'yi de (Windows Arama) devre dışı bırakır.\n\nÖnerilen yol Print Screen tuşudur.\n\nYine de devam edilsin mi? (Masaüstünü yeniden başlatır)",
        ["ConfirmWinShiftSTitle"] = "Win+Shift+S'yi devral",
        ["ConfirmRevert"] = "Yerel Windows kısayollarını yedekten geri yükler ve Klip'u Ctrl+Shift+V / Ctrl+Shift+S kısayollarına döndürür. Masaüstünü yeniden başlatır.\n\nDevam edilsin mi?",
        ["ConfirmRevertTitle"] = "Geri al",
        ["BusyApplying"] = "Kayıt defteri değişiklikleri uygulanıyor ve masaüstü yeniden başlatılıyor...",
        ["BusyReverting"] = "Kayıt defteri değişiklikleri geri alınıyor ve masaüstü yeniden başlatılıyor...",
        ["ResultWinVOk"] = "Tamam! Win+V artık Klip'u açıyor.",
        ["ResultUacCancelled"] = "UAC'de iptal edildi. HKLM'de hiçbir şey değiştirilmedi.",
        ["ResultWinVFail"] = "Win+V kaydedilemedi. Günlüğe bakın: %LocalAppData%\\Klip.",
        ["ResultPrtScOk"] = "Tamam! Print Screen artık Klip yakalamasını açıyor.",
        ["ResultPrtScConflict"] = "PrtSc serbest bırakıldı ama tuşu başka bir uygulama tutuyor.",
        ["ResultWinShiftSOk"] = "Tamam! Win+Shift+S artık Klip yakalamasını açıyor.",
        ["ResultWinShiftSFail"] = "Win+Shift+S kaydedilemedi.",
        ["ResultReverted"] = "Yerel Windows kısayolları geri yüklendi.",
        ["HotkeyUpdated"] = "Kısayol güncellendi: {0}",
        ["HotkeyConflict"] = "{0} başka bir uygulamayla çakışıyor.",
    };
}
