namespace Klip.App.Localization.Tables;

/// <summary>Tabela de strings: 中文（简体）.</summary>
internal static class Zh
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["TrayOpenHistory"] = "打开历史记录",
        ["TrayCapture"] = "屏幕截图",
        ["TraySettings"] = "设置",
        ["TrayExit"] = "退出",
        ["TrayPauseHistory"] = "暂停剪贴板历史记录",
        ["TrayResumeHistory"] = "恢复剪贴板历史记录",
        ["TrayPauseTooltip"] = "暂停期间，复制的内容不会保存到历史记录",

        ["NotifyCaptureCopied"] = "截图已复制 ({0}x{1})",
        ["NotifyClickToEdit"] = "单击以编辑",
        ["NotifyHotkeyConflict"] = "快捷键 {0} 已被其他应用占用",
        ["NotifyMemoryLimit"] = "已达到内存限制。截图已自动完成",
        ["NotifyFramesDiscarded"] = "部分片段已被丢弃。下次请滚动慢一些",

        ["TabRecent"] = "最近",
        ["TabFavorites"] = "收藏",
        ["TabImages"] = "图像和截图",
        ["TabText"] = "文本",
        ["TabFiles"] = "文件",
        ["FilterByDate"] = "按日期筛选",
        ["SearchPlaceholder"] = "搜索历史记录",
        ["EmptyHistory"] = "这里还没有内容。复制点什么吧！",
        ["FooterHints"] = "Enter 粘贴 · Shift+Enter 纯文本 · Del 删除",
        ["ClearAll"] = "全部清除",
        ["ClearAllTooltip"] = "移除未固定且未收藏的项目",
        ["PinTooltip"] = "固定到顶部 (Ctrl+P)",
        ["FavoriteTooltip"] = "收藏 (Ctrl+D)",
        ["MoreOptions"] = "更多选项",
        ["PinnedBadge"] = "已固定",
        ["FavoriteBadge"] = "已收藏",
        ["DateToday"] = "今天",
        ["DateYesterday"] = "昨天",
        ["DateLast7"] = "过去 7 天",
        ["DateLast30"] = "过去 30 天",
        ["DateAll"] = "全部时间",
        ["MenuPaste"] = "粘贴",
        ["MenuPastePlain"] = "以纯文本粘贴",
        ["MenuCopy"] = "复制",
        ["MenuSaveAs"] = "另存为...",
        ["MenuOpenInEditor"] = "在编辑器中打开",
        ["MenuPin"] = "固定到顶部",
        ["MenuUnpin"] = "取消固定",
        ["MenuFavorite"] = "收藏",
        ["MenuUnfavorite"] = "从收藏中移除",
        ["MenuDelete"] = "删除",
        ["GroupPinned"] = "已固定",
        ["GroupRecent"] = "最近",
        ["ItemImage"] = "图像",
        ["TimeNow"] = "刚刚",
        ["TimeYesterday"] = "昨天",
        ["PngFilter"] = "PNG 图像|*.png",

        ["ModeRectangle"] = "矩形",
        ["ModeWindow"] = "窗口",
        ["ModeFullscreen"] = "全屏",
        ["ModeScrolling"] = "滚动截图（在滚动区域上拖动）",
        ["CloseEsc"] = "关闭 (Esc)",

        ["PanoramicTitle"] = "滚动截图",
        ["PanoramicInstruction"] = "按自己的节奏滚动高亮区域，\n保持平稳并朝一个方向滚动。",
        ["PanoramicCaptured"] = "已捕获 {0} px",
        ["PanoramicSlowDown"] = "请滚动慢一些",
        ["PanoramicDone"] = "完成",
        ["PanoramicCancel"] = "取消",
        ["CaptureTitleScreen"] = "屏幕截图",
        ["CaptureTitleScrolling"] = "滚动截图",

        ["EditorTitle"] = "Klip 编辑器",
        ["ToolSelect"] = "选择并移动 (V)",
        ["ToolPen"] = "画笔 (P)",
        ["ToolHighlighter"] = "荧光笔 (H)",
        ["ToolEraser"] = "橡皮擦 (E)",
        ["ToolRect"] = "矩形 (R)",
        ["ToolEllipse"] = "椭圆 (O)",
        ["ToolLine"] = "直线 (L)",
        ["ToolArrow"] = "箭头 (A)",
        ["ToolText"] = "文本 (T)",
        ["ToolCrop"] = "裁剪 (C)：Enter 应用，Esc 取消",
        ["ToolRemoveBg"] = "移除背景（与边缘相连的纯色背景将变为透明）",
        ["ToolUndo"] = "撤消 (Ctrl+Z)",
        ["ToolRedo"] = "重做 (Ctrl+Y)",
        ["ToolAutoCopy"] = "每次编辑后自动复制",
        ["ToolSaveAs"] = "另存为... (Ctrl+S)",
        ["Thickness"] = "粗细",
        ["Zoom"] = "缩放",
        ["StatusCopied"] = "已复制",
        ["BgRemoved"] = "背景已移除（{0} px 透明）",
        ["BgNotFound"] = "未在边缘检测到均匀背景",
        ["SaveImageFilter"] = "PNG 图像|*.png|JPEG 图像|*.jpg",

        ["SettingsTitle"] = "Klip 设置",
        ["SectionNativeHotkeys"] = "Windows 原生快捷键",
        ["CardWinVTitle"] = "将 Win+V 用于 Klip",
        ["CardWinVCaption"] = "禁用原生历史记录面板（注册表 DisabledHotkeys 值）并将 Win+V 注册给 Klip。过程中会重启桌面。可随时还原。",
        ["TakeWinV"] = "接管 Win+V",
        ["CardCaptureKeyTitle"] = "原生截图快捷键",
        ["CardCaptureKeyCaption"] = "Print Screen（推荐）：从原生 Snipping Tool 释放 PrtSc 键，无副作用。Win+Shift+S：同时会禁用 Win+S（Windows 搜索），这是 Windows 的限制。",
        ["UsePrintScreen"] = "使用 Print Screen",
        ["UseWinShiftS"] = "使用 Win+Shift+S",
        ["CardRevertTitle"] = "全部还原",
        ["CardRevertCaption"] = "将 Windows 原生快捷键完全恢复原样（自动备份），并将 Klip 恢复为 Ctrl+Shift+V / Ctrl+Shift+S。",
        ["Revert"] = "还原",
        ["SectionAppHotkeys"] = "Klip 快捷键",
        ["OpenHistoryHotkey"] = "打开历史记录",
        ["NewCaptureHotkey"] = "新建截图",
        ["HotkeyHint"] = "单击输入框并按下组合键",
        ["SectionGeneral"] = "常规",
        ["StartWithWindows"] = "随 Windows 启动",
        ["LanguageTitle"] = "语言",
        ["LanguageCaption"] = "默认：Windows 语言。更改立即生效。",
        ["LanguageSystem"] = "系统",
        ["LanguageRestart"] = "语言已保存。请重启 Klip 以应用。",
        ["SectionClipboard"] = "剪贴板历史记录",
        ["MaxItemsTitle"] = "最大项目数",
        ["MaxItemsCaption"] = "已固定和已收藏的项目永远不会被移除。0 = 无限制。",
        ["SectionCapture"] = "屏幕截图",
        ["AutoSaveTitle"] = "自动保存截图",
        ["AutoSaveCaption"] = "图片\\Screenshots 文件夹，Windows 默认位置",
        ["CadenceTitle"] = "滚动截图节奏",
        ["CadenceCaption"] = "滚动时的帧间隔（默认 150 ms；如果电脑卡顿请调大）",
        ["SectionAbout"] = "关于",
        ["AboutText"] = "Klip：Windows 11 原生风格的剪贴板历史记录和屏幕截图。本地优先：任何数据都不会离开您的电脑。",
        ["ItemsInHistory"] = "历史记录中有 {0} 个项目。",

        ["WinVActive"] = "已启用：Win+V 打开 Klip。",
        ["WinVFreedNotBound"] = "Win+V 已在注册表中释放，但尚未分配给 Klip。",
        ["WinVNative"] = "Win+V 归 Windows 所有（原生面板）。",
        ["ManagedPolicyWarning"] = "（此计算机受企业策略管理：更改可能被域还原。）",
        ["PrtScActive"] = "已启用：Print Screen 打开 Klip 截图。",
        ["WinShiftSActive"] = "已启用：Win+Shift+S 打开 Klip 截图（Win+S 已禁用）。",
        ["PrtScFreeInfo"] = "PrtSc 在系统中已释放；Klip 截图快捷键为 {0}。",
        ["PrtScNativeInfo"] = "PrtSc 打开原生 Snipping Tool；Klip 截图快捷键为 {0}。",
        ["ConfirmWinV"] = "Klip 将执行以下操作：\n\n1. 向注册表 (HKCU) 的 DisabledHotkeys 值添加 'V'，并自动备份。\n2. 重启桌面（Explorer 窗口将关闭；任务栏会闪烁）。\n3. 将 Win+V 注册给 Klip。\n\n原生历史记录面板将不再打开。可通过\"还原\"按钮撤销。\n\n是否继续？",
        ["ConfirmWinVTitle"] = "接管 Win+V",
        ["ConfirmHklm"] = "Windows 仍占用着 Win+V（在 24H2 或更新版本上常见）。\n\n备选方案将通过 HKLM 禁用原生历史记录功能（需要管理员权限）。在还原之前，\"剪贴板\"页面将从 Windows 设置中消失。\n\n是否应用备选方案？",
        ["ConfirmHklmTitle"] = "备选方案（需要管理员权限）",
        ["ConfirmWinShiftS"] = "注意：由于 Windows 的限制，禁用 Win+Shift+S 也会同时禁用 Win+S（Windows 搜索）。\n\n推荐的方式是使用 Print Screen 键。\n\n仍要继续吗？（将重启桌面）",
        ["ConfirmWinShiftSTitle"] = "接管 Win+Shift+S",
        ["ConfirmRevert"] = "从备份恢复 Windows 原生快捷键，并将 Klip 恢复为 Ctrl+Shift+V / Ctrl+Shift+S。将重启桌面。\n\n是否继续？",
        ["ConfirmRevertTitle"] = "还原",
        ["BusyApplying"] = "正在应用注册表更改并重启桌面...",
        ["BusyReverting"] = "正在还原注册表更改并重启桌面...",
        ["ResultWinVOk"] = "完成！Win+V 现在会打开 Klip。",
        ["ResultUacCancelled"] = "已在 UAC 中取消。HKLM 未做任何更改。",
        ["ResultWinVFail"] = "无法注册 Win+V。请查看 %LocalAppData%\\Klip 中的日志。",
        ["ResultPrtScOk"] = "完成！Print Screen 现在会打开 Klip 截图。",
        ["ResultPrtScConflict"] = "PrtSc 已释放，但另一个应用占用着该键。",
        ["ResultWinShiftSOk"] = "完成！Win+Shift+S 现在会打开 Klip 截图。",
        ["ResultWinShiftSFail"] = "无法注册 Win+Shift+S。",
        ["ResultReverted"] = "Windows 原生快捷键已恢复。",
        ["HotkeyUpdated"] = "快捷键已更新：{0}",
        ["HotkeyConflict"] = "{0} 与另一个应用程序冲突。",
    };
}
